Repository dogandme/frontend, pull requests merged in 2024-11, with the labels that each got.

#430 [Feat] KMeans clustering 이용한 마커 군집화 , useKMeansClustering 생성
  src/entities/map/ui/lib/cluster.ts
  src/entities/map/ui/lib/index.ts
Labels: 👶 기능

#397 [Feat] OverlayOption 인수 추가 & 마킹 폼 닫기 컨펌 모달 호출 위치 변경
  src/features/map/ui/mapControlButton.tsx
  src/features/marking/ui/markingFormCloseModal.tsx
  src/features/marking/ui/markingFormModal.tsx
Labels: 👶 기능, ⚒️ 리팩토링

#431 [Refactor] 마킹 모달 공개 범위 기본값 설정
  eslint.config.js
  src/app/MainLayout.tsx
  src/entities/follow/api/getFollowerList.ts
  src/entities/follow/api/getFollowingList.ts
  src/entities/follow/constants/endpoint.ts
  src/entities/marking/api/getMarkingList.ts
  src/entities/marking/api/getTemporaryMarkingList.ts
  src/entities/marking/constants/index.ts
  src/features/marking/api/postAddMarking.tsx
  src/features/marking/api/postAddTempMarking.tsx
  src/features/marking/constants/index.ts
  src/features/marking/store/markingForm.ts
  src/features/marking/store/tempMarkingForm.tsx
  src/features/marking/ui/markingFormModal.stories.tsx
  src/features/marking/ui/markingFormModal.tsx
  src/features/marking/ui/tempMarkingFormModal.tsx
  src/mocks/handler.ts
  src/widgets/marking/api/getDashboardMarkingThumbnail.ts
  src/widgets/marking/constants/index.ts
  src/widgets/marking/ui/temporaryMarkingItem.tsx
Labels: 👶 기능, ⚒️ 리팩토링

#408 [Feat] 동네마킹 바텀시트 주소 표시
  src/entities/marking/api/getAddressFromLatLng.ts
  src/widgets/map/ui/localMarkingList.tsx
  src/widgets/map/ui/mapInitializer.tsx
Labels: 👶 기능

#435 [Refactor] 팔로잉 팔로우 토글 리팩토링 , 마킹 아이템 팔로잉 팔로우 아이템 장착
  src/features/follow/ui/followingToggle.tsx
  src/features/marking/ui/markingItem.stories.tsx
  src/features/marking/ui/markingItem.tsx
  src/mocks/data/markingList.ts
  src/widgets/follow/followerUserItem.tsx
  src/widgets/follow/followingUserItem.tsx
  src/widgets/map/ui/placeMarkingList.tsx
  src/widgets/profile/ui/profileOverview.tsx
Labels: 👶 기능, ⚒️ 리팩토링

#440 [Feat] 펫 정보 등록 안한 유저 , 마킹을 남기지 않은 유저 퍼블리싱
  src/mocks/data/otherUser.ts
  src/mocks/data/profileMarking.ts
  src/mocks/handler.ts
  src/pages/[nickname]/otherProfilePage.tsx
  src/widgets/marking/ui/markingThumbnailGrid.tsx
Labels: 👶 기능

#434 [Feat] 마킹 삭제하기
  src/features/marking/api/deleteMarking.ts
  src/features/marking/ui/markingItem.tsx
  src/shared/lib/dropdown.ts
  src/shared/lib/index.ts
  src/widgets/map/ui/placeMarkingList.tsx
Labels: 👶 기능

#446 [ Fix] useDropdown 오타 수정
  src/shared/lib/dropdown.ts
Labels: 🐛 버그

#421 [Feat] 스낵바 리액트 쿼리 클라이언트 , 전역에 달기
  src/app/ReactQueryProvider/constants.ts
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/features/auth/api/postAddPetInfo.ts
  src/features/auth/api/postLogin.ts
  src/features/auth/api/postSignUpByEmail.ts
  src/features/auth/api/putAddUserInfo.ts
  src/features/auth/store/petInformationForm.ts
  src/features/auth/ui/LoginForm.tsx
  src/features/auth/ui/UserInfoRegistrationForm.tsx
  src/features/auth/ui/petInformationForm.tsx
  src/features/map/hooks/useCurrentLocation.ts
  src/features/map/ui/mapControlButton.tsx
  src/features/marking/api/postAddTempMarking.tsx
  src/features/marking/ui/markingFormModal.tsx
  src/features/setting/api/deleteAccount.tsx
  src/features/setting/api/postChangeRegion.ts
  src/features/setting/api/postLogout.ts
  src/features/setting/ui/passwordChangeModal.tsx
  src/features/setting/ui/setting.tsx
  src/mocks/handler.ts
  src/shared/lib/snackbar.tsx
Labels: 👶 기능, 🐛 버그

#455 [Feat] 펫 인포 폼 종 검색 기능 추가
  src/features/auth/constants/form.ts
  src/features/auth/store/petInformationForm.ts
  src/features/auth/ui/petInformationForm.tsx
Labels: 👶 기능, 🐛 버그

#457 [Refactor] 이메일 회원가입 폼 리팩토링
  src/entities/auth/ui/Input.tsx
  src/features/auth/api/postCheckCode.ts
  src/features/auth/api/postSendCode.ts
  src/features/auth/store/form.ts
  src/features/auth/store/index.ts
  src/features/auth/store/signUpByEmailForm.ts
  src/features/auth/ui/SignUpByEmailForm.stories.tsx
  src/features/auth/ui/index.ts
  src/features/auth/ui/signUpByEmailForm.tsx
  src/mocks/handler.ts
  src/pages/sign-up/page.tsx
Labels: ⚒️ 리팩토링

#458 [Feat] 마킹 클러스터링 적용 & 클러스터링 캐싱 로직 추가
  src/entities/map/constants/index.ts
  src/entities/map/constants/tiling.ts
  src/entities/map/lib/index.ts
  src/entities/map/lib/tiling.ts
  src/entities/map/ui/customMarker.tsx
  src/entities/map/ui/lib/cluster.ts
  src/entities/map/ui/lib/index.ts
  src/entities/map/ui/pin.stories.tsx
  src/entities/map/ui/pin.tsx
  src/entities/marking/api/getBoundaryMarkerList.ts
  src/entities/marking/api/getMyMakerList.ts
  src/features/map/store/map.ts
  src/mocks/data/markingList.ts
  src/pages/map/my/page.tsx
  src/pages/map/page.tsx
  src/pages/map/place/page.tsx
  src/widgets/map/ui/googleMaps.tsx
Labels: 👶 기능, ⚒️ 리팩토링

#462 [Feat] [동네 마킹] 버튼을 클릭하면 동네 마킹 바텀 시트 노출
  src/entities/marking/api/getAddressFromLatLng.ts
  src/features/map/ui/mapControlButton.tsx
  src/widgets/map/ui/localMarkingList.tsx
Labels: 👶 기능, 🐛 버그

#461 [Fix] 내 마킹 페이지에서 sortType 기본값 설정 및 필터 기능 구현
  src/features/map/ui/mapControlButton.tsx
  src/widgets/map/ui/mapInitializer.tsx
  src/widgets/map/ui/myMarkingList.tsx
Labels: ⚒️ 리팩토링, 🐛 버그

#467 [Refactor] 동네마킹 api url 경로 수정
  src/entities/marking/api/getMarkingList.ts
  src/entities/marking/api/getUserMarkingList.ts
  src/entities/marking/constants/index.ts
  src/widgets/map/ui/localMarkingList.tsx
  src/widgets/map/ui/placeMarkingList.tsx
Labels: ⚒️ 리팩토링

#468 [Feat] 좋아요 , 북마크 누른 마커 가져오기 쿼리문 생성
  src/entities/marking/api/getMyActivityMarkerList.ts
  src/entities/marking/api/index.ts
  src/entities/marking/constants/index.ts
  src/mocks/data/markerList.ts
  src/mocks/handler.ts
  src/widgets/map/ui/myActivityList.tsx
Labels: 👶 기능

#447 [Feat] 마킹 아이템 수정 모달 달기
  src/entities/marking/api/getBoundaryMarkerList.ts
  src/entities/marking/api/getMyLikedMarkingList.ts
  src/entities/marking/api/getMyMakerList.ts
  src/entities/marking/api/getMySavedMarkerList.ts
  src/entities/marking/api/getTemporaryMarkingList.ts
  src/entities/marking/api/getUserMarkingList.ts
  src/features/map/ui/mapControlButton.tsx
  src/features/marking/api/index.ts
  src/features/marking/api/postAddMarking.tsx
  src/features/marking/api/postAddTempMarking.tsx
  src/features/marking/api/putModifyMarking.ts
  src/features/marking/api/putModifyTempMarking.ts
  src/features/marking/constants/endPoint.ts
  src/features/marking/lib/index.ts
  src/features/marking/lib/markingModal.ts
  src/features/marking/store/editMarkingForm.tsx
  src/features/marking/store/index.ts
  src/features/marking/ui/editMarkingFormModal.tsx
  src/features/marking/ui/index.ts
  src/features/marking/ui/markingBookmarkToggle.tsx
  src/features/marking/ui/markingItem.tsx
  src/features/marking/ui/markingLikeToggle.tsx
  src/pages/[nickname]/marking/page.tsx
  src/shared/lib/overlay.tsx
  src/widgets/map/ui/myActivityList.tsx
  src/widgets/map/ui/myMarkingList.tsx
  src/widgets/map/ui/placeMarkingList.tsx
  src/widgets/marking/store/index.ts
  src/widgets/marking/store/markingItem.ts
  src/widgets/marking/ui/index.ts
  src/widgets/marking/ui/markingItem.stories.tsx
  src/widgets/marking/ui/markingItem.tsx
  src/widgets/marking/ui/temporaryMarkingItem.tsx
Labels: 👶 기능, ⚒️ 리팩토링

#444 [Feat] 스낵바 애니메이션 생성 및 타이머 로직 리팩토링
  src/global.css
  src/shared/lib/snackbar.tsx
  src/shared/ui/snackbar/Snackbar.stories.tsx
  src/shared/ui/snackbar/Snackbar.tsx
Labels: 👶 기능

#464 [Chore] eslint ci 설정
  .github/workflows/eslint.yml
  package.json
Labels: ⚙️ 환경 설정

#471 [Refactor] 쿼리키 팩토리 패턴으로 리팩토링
  src/entities/auth/api/getMyInfo.ts
  src/entities/auth/api/getRegion.ts
  src/entities/auth/constants/index.ts
  src/entities/auth/constants/queryKey.ts
  src/entities/follow/api/getFollowerList.ts
  src/entities/follow/api/getFollowingList.ts
  src/entities/follow/constants/index.ts
  src/entities/follow/constants/queryKey.ts
  src/entities/marking/api/getAddressFromLatLng.ts
  src/entities/marking/api/getBoundaryMarkerList.ts
  src/entities/marking/api/getDashboardMarkingThumbnail.ts
  src/entities/marking/api/getMarkingDetail.ts
  src/entities/marking/api/getMarkingList.ts
  src/entities/marking/api/getMyActivityMarkerList.ts
  src/entities/marking/api/getMyLikedMarkingList.ts
  src/entities/marking/api/getMyMakerList.ts
  src/entities/marking/api/getMySavedMarkerList.ts
  src/entities/marking/api/getTemporaryMarkingList.ts
  src/entities/marking/api/getUserMarkingList.ts
  src/entities/marking/api/index.ts
  src/entities/marking/constants/index.ts
  src/entities/marking/constants/queryKey.ts
  src/entities/profile/api/getProfile.ts
  src/entities/profile/constants/index.ts
  src/entities/profile/constants/queryKey.ts
  src/features/auth/api/putChangeNickname.ts
  src/features/marking/api/deleteLikeMarking.ts
  src/features/marking/api/deleteSavedMarking.ts
  src/features/marking/api/deleteTemporaryMarking.ts
  src/features/setting/api/postChangeRegion.ts
  src/features/setting/api/putChangeAge.tsx
  src/features/setting/api/putChangeGender.ts
  src/features/setting/api/putChangePetInfo.ts
  src/features/setting/api/putSetPassword.tsx
  src/widgets/marking/api/index.ts
  src/widgets/marking/constants/index.ts
  src/widgets/marking/ui/markingThumbnailGrid.tsx
Labels: ⚒️ 리팩토링

#479 [Feat] 클러스터핀 제거 , density props 제거
  src/entities/map/ui/customMarker.tsx
Labels: 👶 기능

#481 [Feat] boundsParams 가 생기고 나면 스낵바가 나타나도록 effect 추가
  src/widgets/map/ui/mapInitializer.tsx
Labels: 👶 기능

#475 [Feat] 현 위치 재검색 선언적으로 수정 & 바운더리 값이 변경 되었을 때에만 나타나도록 수정
  src/features/map/hooks/useMapQueryParams.ts
  src/features/map/store/map.ts
  src/features/map/ui/mapControlButton.tsx
  src/features/map/ui/markingResearchButton.tsx
  src/widgets/map/ui/googleMaps.tsx
  src/widgets/map/ui/mapControlWidget.tsx
  src/widgets/map/ui/mapInitializer.tsx
Labels: 👶 기능

#488 [Feat] getMyInfo gcTime , staleTime infinity 로 변경
  src/entities/auth/api/getMyInfo.ts
Labels: 🚀 최적화

#489 [Feat] 유효하지 않은 토큰으로 요청했을 때 재발급 받고 요청 재시도
  src/app/DevTools.tsx
  src/app/ReactQueryProvider/errorHandlers.ts
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/mocks/handler.ts
  src/pages/[nickname]/myProfilePage.tsx
  src/pages/[nickname]/otherProfilePage.tsx
  src/pages/[nickname]/page.tsx
Labels: 👶 기능

#491 [Hotfix] 줌 레벨이 15일 때 타일이 그려지지 않던 버그 수정
  src/entities/map/constants/tiling.ts
  src/entities/map/lib/tiling.ts
Labels: 🐛 버그

#484 [Feat] 맵 이니셜라이저 버그 수정 & 이 장소 마킹 라우팅 및 API 요청
  src/entities/map/lib/tiling.ts
  src/entities/map/ui/customMarker.tsx
  src/entities/marking/api/getBoundaryMarkerList.ts
  src/features/map/hooks/index.ts
  src/features/map/hooks/useMapQueryParams.ts
  src/features/map/hooks/usePlaceQueryParams.ts
  src/features/map/ui/markingResearchButton.tsx
  src/pages/map/page.tsx
  src/pages/map/place/page.tsx
  src/widgets/map/ui/localMarkingList.tsx
  src/widgets/map/ui/mapInitializer.tsx
  src/widgets/map/ui/placeMarkingList.tsx
Labels: 👶 기능, ⚒️ 리팩토링, 🐛 버그

#473 [Hotfix] fullPageModal 의 overlayWrapper 너비 수정
  src/app/OverlayPortal.tsx
Labels: 🐛 버그

#494 [Hotfix] 로그인 하지 않은 유저에게서 이 장소 마킹이 나타나지 않던 문제 해결
  src/entities/profile/api/getProfile.ts
  src/widgets/map/ui/placeMarkingList.tsx
  src/widgets/marking/ui/markingItem.tsx
Labels: 🐛 버그

#486 [Feat] 마킹 아이템 더 보기 버튼 장착
  src/mocks/data/markingList.ts
  src/mocks/data/tempMarkingList.ts
  src/widgets/marking/ui/markingItem.tsx
  src/widgets/marking/ui/temporaryMarkingItem.tsx
Labels: 👶 기능

#498 [Feat] 권한에 따라 라우팅 제한
  src/app/DevTools.tsx
  src/app/api.ts
  src/app/router.tsx
  src/features/auth/api/postAddPetInfo.ts
  src/features/auth/api/postLogin.ts
  src/features/auth/api/postSignUpByEmail.ts
  src/features/auth/api/putAddUserInfo.ts
  src/features/auth/ui/hyperlinks.tsx
  src/pages/[nickname]/follower/page.tsx
  src/pages/[nickname]/following/page.tsx
  src/pages/[nickname]/marking/page.tsx
  src/pages/[nickname]/notFoundUser.tsx
  src/pages/[nickname]/page.tsx
  src/pages/authError.tsx
  src/pages/errorBoundary.tsx
  src/pages/index.ts
  src/pages/map/layout.tsx
  src/pages/map/my/page.tsx
  src/pages/setting/edit-info/page.tsx
  src/pages/setting/manage-account/page.tsx
  src/pages/setting/page.tsx
  src/pages/sign-up/page.tsx
  src/pages/sign-up/pet-info/page.tsx
  src/pages/sign-up/user-info/page.tsx
  src/pages/temporary-marking/page.tsx
  src/shared/constants/index.ts
  src/shared/lib/auth.tsx
  src/shared/lib/index.ts
  src/shared/store/auth.ts
  src/widgets/map/ui/myActivityList.tsx
Labels: 👶 기능

#502 [Feat] 마킹 리스트 바텀 시트 리팩토링 및 빈 마킹 리스트 생성
  src/entities/marking/api/getMarkingDetail.ts
  src/entities/marking/api/getMarkingList.ts
  src/entities/marking/api/getUserMarkingList.ts
  src/entities/marking/ui/emptyMarkingGrid.tsx
  src/entities/marking/ui/index.ts
  src/entities/profile/api/getProfile.ts
  src/features/marking/ui/markingFilter.tsx
  src/mocks/handler.ts
  src/pages/[nickname]/follower/page.tsx
  src/pages/[nickname]/following/page.tsx
  src/pages/[nickname]/marking/page.tsx
  src/pages/[nickname]/myProfilePage.tsx
  src/pages/[nickname]/otherProfilePage.tsx
  src/pages/map/my/page.tsx
  src/pages/map/place/page.tsx
  src/widgets/map/ui/index.ts
  src/widgets/map/ui/localMarkingListBottomSheet.tsx
  src/widgets/map/ui/myActivityList.tsx
  src/widgets/map/ui/myMarkingList.tsx
  src/widgets/map/ui/myMarkingListBottomSheet.tsx
  src/widgets/map/ui/placeMarkingList.tsx
  src/widgets/map/ui/placeMarkingListBottomSheet.tsx
  src/widgets/marking/store/markingItem.ts
  src/widgets/marking/ui/markingItem.tsx
  src/widgets/marking/ui/markingThumbnailGrid.tsx
Labels: 👶 기능, ⚒️ 리팩토링

#507 [Refactor] NavigationBar props children으로 받도록 변경
  src/features/auth/ui/authNavigationBar.tsx
  src/pages/[nickname]/follower/page.tsx
  src/pages/[nickname]/following/page.tsx
  src/pages/[nickname]/marking/page.tsx
  src/pages/[nickname]/myProfilePage.tsx
  src/pages/[nickname]/otherProfilePage.tsx
  src/pages/setting/edit-info/page.tsx
  src/pages/setting/manage-account/page.tsx
  src/pages/setting/page.tsx
  src/pages/sign-up/page.tsx
  src/pages/temporary-marking/page.tsx
  src/shared/ui/navigationbar/BackwardNavigationBar.tsx
  src/shared/ui/navigationbar/CloseNavigationBar.tsx
  src/shared/ui/navigationbar/Navigation.style.ts
  src/shared/ui/navigationbar/NavigationBar.tsx
  src/widgets/map/ui/placeMarkingListBottomSheet.tsx
Labels: ⚒️ 리팩토링

#508 [Refactor] 이메일 회원가입 폼 리팩토링
  src/features/auth/api/postCheckCode.ts
  src/features/auth/api/postSendCode.ts
  src/features/auth/constants/form.ts
  src/features/auth/store/index.ts
  src/features/auth/store/verifyEmail.tsx
  src/features/auth/ui/signUpByEmailForm.tsx
  src/shared/ui/input/Input.tsx
Labels: ⚒️ 리팩토링, 🐛 버그

#505 [Feat] query 로딩 상태에 대해 스켈레톤 처리
  src/features/marking/ui/markingFormModal.tsx
  src/features/setting/hooks/index.ts
  src/features/setting/hooks/useSettingPermission.tsx
  src/global.css
  src/mocks/data/otherUser.ts
  src/mocks/handler.ts
  src/pages/[nickname]/follower/page.tsx
  src/pages/[nickname]/following/page.tsx
  src/pages/[nickname]/loading.tsx
  src/pages/[nickname]/marking/page.tsx
  src/pages/[nickname]/myProfilePage.tsx
  src/pages/[nickname]/otherProfilePage.tsx
  src/pages/setting/edit-info/page.tsx
  src/pages/setting/manage-account/page.tsx
  src/pages/temporary-marking/page.tsx
  src/widgets/follow/followItemContainer.tsx
  src/widgets/map/ui/localMarkingListBottomSheet.tsx
  src/widgets/map/ui/myActivityList.tsx
  src/widgets/map/ui/myMarkingListBottomSheet.tsx
  src/widgets/map/ui/placeMarkingListBottomSheet.tsx
  src/widgets/marking/ui/markingItem.tsx
  src/widgets/marking/ui/markingThumbnailGrid.tsx
  src/widgets/marking/ui/temporaryMarkingItem.tsx
  src/widgets/profile/ui/profileOverview.tsx
Labels: 👶 기능

#514 [Fix] 유효하지 않은 refresh token으로 access token 재발급했을 때 발생한 무한 요청 버그 해결 및 DevTools 수정
  src/app/AppProviderLayout.tsx
  src/app/DevTools.tsx
  src/app/MainLayout.tsx
  src/app/ReactQueryProvider/errorHandlers.ts
  src/features/auth/ui/LoginForm.stories.tsx
  src/features/auth/ui/SignUpByEmailForm.stories.tsx
  src/features/auth/ui/petInformationForm.stories.tsx
  src/features/marking/ui/markingFormModal.stories.tsx
  src/main.tsx
  src/mocks/data/user.ts
  src/mocks/handler.ts
  src/widgets/marking/ui/markingItem.stories.tsx
Labels: ⚒️ 리팩토링, 🐛 버그
