Repository dogandme/frontend, pull requests merged in 2024-09, with the labels that each got.

#95 [Refactor] 기본 정보 입력 api 요청하는 로직 오타 수정
  src/features/auth/api/signUp.ts
  src/features/auth/constants/endpoint.ts
Labels: ⚒️ 리팩토링

#94 [Hotfix] OAuth 로그인 인증 과정 관련 로직 수정
  src/features/auth/api/login.ts
  src/features/auth/api/petinfo.ts
  src/features/auth/ui/PetInfoForm.stories.tsx
  src/features/auth/ui/PetInfoForm.tsx
  src/features/auth/ui/hyperlinks.tsx
  src/shared/lib/cookie.ts
  src/shared/lib/index.ts
Labels: 👶 기능

#98 [Feat] 페이지 라우팅 경로 수정
  src/app/MobileLayout.tsx
  src/app/QueryClient.tsx
  src/app/index.ts
  src/app/router.tsx
  src/main.tsx
  src/pages/layout.tsx
  src/pages/login/email/email.stories.tsx
  src/pages/login/layout.tsx
  src/pages/login/login.stories.tsx
  src/pages/login/page.tsx
  src/widgets/navigationbar/ui/BackwardNavigationBar.tsx
Labels: 👶 기능

#99 [Feat] / 페이지 레이아웃과 MainFooter 컴포넌트 생성
  src/app/MobileLayout.tsx
  src/app/router.tsx
  src/global.css
  src/pages/layout.tsx
  src/shared/assets/community.svg
  src/shared/assets/compass.svg
  src/shared/assets/map.svg
  src/shared/assets/notification.svg
  src/shared/constants/index.ts
  src/shared/ui/icon/index.ts
  src/widgets/footer/ui/MainFooter.tsx
  src/widgets/footer/ui/footer.stories.tsx
  src/widgets/footer/ui/footer.style.ts
  src/widgets/footer/ui/index.ts
  src/widgets/navigationbar/ui/GlobalNavigationBar.tsx
  src/widgets/navigationbar/ui/index.ts
  src/widgets/navigationbar/ui/navigationbar.stories.tsx
Labels: 👶 기능

#101 [Feat] Floating Button 컴포넌트 생성
  src/entities/map/ui/FloatingButton.stories.tsx
  src/entities/map/ui/FloatingButton.styles.ts
  src/entities/map/ui/FloatingButton.tsx
  src/entities/map/ui/index.ts
  src/shared/assets/location.svg
  src/shared/assets/my-location.svg
  src/shared/assets/start.svg
  src/shared/ui/icon/index.ts
  tailwind.config.js
Labels: 👶 기능

#105 [Chore] react-modal-sheet 설치
  package-lock.json
  package.json
  src/global.css
  src/shared/ui/bottomSheet/BottomSheet.stories.tsx
Labels: ⚙️ 환경 설정

#110 [Feat] Authorization 기능 변화에 따른 userId걷어내기
  src/features/auth/api/petinfo.ts
  src/features/auth/ui/LoginForm.stories.tsx
  src/features/auth/ui/LoginForm.tsx
  src/features/auth/ui/PetInfoForm.stories.tsx
  src/features/auth/ui/PetInfoForm.tsx
  src/shared/store/auth.ts
Labels: 👶 기능

#112 [Feat] Google 정책에 따라 기본 로고 , 저작권 기본 문구 없애고 커스텀 로고 및 문구 작성
  public/google_on_white.png
  src/global.css
  src/pages/layout.tsx
  src/pages/map/page.tsx
  src/widgets/footer/ui/MainFooter.tsx
  src/widgets/footer/ui/index.ts
  src/widgets/map/ui/GoogleMapsCopyRight.tsx
  src/widgets/map/ui/MainFooter.stories.tsx
  src/widgets/map/ui/MainFooter.style.ts
  src/widgets/map/ui/MainFooter.tsx
  src/widgets/map/ui/index.ts
  src/widgets/navigationbar/ui/GlobalNavigationBar.tsx
Labels: 👶 기능

#113 [Feat] List, Select 컴포넌트 생성
  src/shared/ui/list/List.stories.tsx
  src/shared/ui/list/List.tsx
  src/shared/ui/list/index.ts
  src/shared/ui/list/list.styles.ts
  src/shared/ui/select/Option.tsx
  src/shared/ui/select/OptionList.tsx
  src/shared/ui/select/Select.stories.tsx
  src/shared/ui/select/Select.tsx
  src/shared/ui/select/SelectBottomSheet.tsx
  src/shared/ui/select/index.ts
  src/shared/ui/select/select.context.tsx
Labels: 👶 기능

#117 [Feat] auth 도메인에서 사용할 SelectOpener 컴포넌트 수정
  src/entities/auth/ui/SelectOpener.stories.tsx
  src/entities/auth/ui/SelectOpener.tsx
Labels: ⚒️ 리팩토링

#116 [Feat] InfoSnackBar 컴포넌트 생성
  src/features/auth/ui/PetInfoForm.stories.tsx
  src/features/auth/ui/PetInfoForm.tsx
  src/shared/lib/overlay.ts
  src/shared/ui/snackbar/Snackbar.stories.tsx
  src/shared/ui/snackbar/Snackbar.tsx
  src/shared/ui/snackbar/index.ts
  tailwind.config.js
Labels: 👶 기능

#121 [Refactor] 기본 정보 입력 폼 리팩토링
  src/features/auth/api/signUp.ts
  src/features/auth/constants/endpoint.ts
  src/features/auth/constants/form.ts
  src/features/auth/lib/index.ts
  src/features/auth/lib/validate.ts
  src/features/auth/store/form.ts
  src/features/auth/ui/UserInfoRegistrationForm.stories.tsx
  src/features/auth/ui/UserInfoRegistrationForm.tsx
  src/shared/ui/select/Select.tsx
  src/shared/ui/select/SelectBottomSheet.tsx
  src/shared/ui/select/select.context.tsx
Labels: ⚒️ 리팩토링

#120 [Feat] 지도에 나타날 커스텀 마커 UI 생성
  src/entities/map/ui/CustomMarker.tsx
  src/entities/map/ui/Pin.stories.tsx
  src/entities/map/ui/Pin.tsx
  src/entities/map/ui/index.ts
  src/features/map/ui/GoogleMaps.tsx
  src/global.css
  src/shared/assets/pin-shadow.svg
  src/shared/ui/icon/index.ts
  tailwind.config.js
Labels: 👶 기능

#124 [Fix] Select.Option에 disabled가 적용 안되는 문제 해결
  src/shared/ui/list/List.stories.tsx
  src/shared/ui/list/List.tsx
  src/shared/ui/select/Option.tsx
  src/shared/ui/select/Select.stories.tsx
  src/shared/ui/select/SelectBottomSheet.tsx
Labels: 🐛 버그

#125 [Fix] SelectOpener가 비활성화되지 않는 문제 해결
  src/entities/auth/ui/SelectOpener.stories.tsx
  src/entities/auth/ui/SelectOpener.tsx
Labels: 🐛 버그

#126 [Feat] PetInfoForm 바텀 시트 기능 추가
  src/features/auth/constants/form.ts
  src/features/auth/ui/PetInfoForm.stories.tsx
  src/features/auth/ui/PetInfoForm.tsx
Labels: 👶 기능

#130 [Refactor] 부적절한 aria 태그 제거 및 수정
  src/entities/auth/ui/Input.tsx
  src/features/auth/ui/LoginForm.stories.tsx
  src/features/auth/ui/LoginForm.tsx
  src/features/auth/ui/PetInfoForm.stories.tsx
  src/features/auth/ui/UserInfoRegistrationForm.stories.tsx
  src/shared/ui/chip/SelectChip.stories.tsx
  src/shared/ui/input/Input.stories.tsx
  src/shared/ui/input/Input.tsx
  src/shared/ui/snackbar/Snackbar.stories.tsx
  src/shared/ui/snackbar/Snackbar.tsx
  src/shared/ui/textarea/TextArea.stories.tsx
  src/shared/ui/textarea/TextArea.tsx
Labels: ⚒️ 리팩토링

#134 [Feat] Modal 컴포넌트 생성
  src/entities/map/ui/FloatingButton.styles.ts
  src/shared/lib/overlay.ts
  src/shared/ui/modal/Modal.mocks.tsx
  src/shared/ui/modal/Modal.stories.tsx
  src/shared/ui/modal/Modal.styles.ts
  src/shared/ui/modal/Modal.tsx
  src/shared/ui/modal/index.ts
  src/shared/ui/snackbar/Snackbar.tsx
  tailwind.config.js
Labels: 👶 기능, ⚒️ 리팩토링

#136 [Chore] FSD 구조에 맞게 import 순서 정렬
  .prettierrc
  package-lock.json
  package.json
  src/app/GoogleMapsProvider.tsx
  src/app/HistoryTracker.tsx
  src/app/router.tsx
  src/entities/auth/assets/index.ts
  src/entities/auth/ui/Checkbox.stories.tsx
  src/entities/auth/ui/Input.stories.tsx
  src/entities/auth/ui/Input.tsx
  src/entities/auth/ui/SelectOpener.stories.tsx
  src/entities/auth/ui/SelectOpener.tsx
  src/entities/map/ui/FloatingButton.stories.tsx
  src/features/auth/api/petinfo.ts
  src/features/auth/ui/LoginForm.stories.tsx
  src/features/auth/ui/LoginForm.tsx
  src/features/auth/ui/PetInfoForm.stories.tsx
  src/features/auth/ui/PetInfoForm.tsx
  src/features/auth/ui/SignUpByEmailForm.stories.tsx
  src/features/auth/ui/SignUpByEmailForm.tsx
  src/features/auth/ui/UserInfoRegistrationForm.stories.tsx
  src/features/auth/ui/UserInfoRegistrationForm.tsx
  src/features/auth/ui/hyperlinks.tsx
  src/features/map/ui/GoogleMaps.tsx
  src/features/map/ui/MarkingButton.tsx
  src/main.tsx
  src/pages/layout.tsx
  src/pages/login/email/email.stories.tsx
  src/pages/login/layout.tsx
  src/pages/login/login.stories.tsx
  src/pages/map/page.tsx
  src/pages/sign-up/page.tsx
  src/pages/sign-up/user-info/page.tsx
  src/shared/ui/badge/Badge.stories.tsx
  src/shared/ui/bottomSheet/BottomSheet.stories.tsx
  src/shared/ui/button/Button.stories.tsx
  src/shared/ui/button/SelectedIconButton.stories.tsx
  src/shared/ui/checkbox/Checkbox.stories.tsx
  src/shared/ui/chip/SelectChip.stories.tsx
  src/shared/ui/icon/Icon.stories.tsx
  src/shared/ui/icon/index.ts
  src/shared/ui/input/Input.stories.tsx
  src/shared/ui/input/Input.tsx
  src/shared/ui/list/List.stories.tsx
  src/shared/ui/overlay/overlay.stories.tsx
  src/shared/ui/select/Select.stories.tsx
  src/shared/ui/select/Select.tsx
  src/shared/ui/snackbar/Snackbar.stories.tsx
  src/shared/ui/textarea/TextArea.stories.tsx
  src/shared/ui/textarea/TextArea.tsx
  src/widgets/map/ui/MainFooter.stories.tsx
  src/widgets/map/ui/MainFooter.tsx
  src/widgets/navigationbar/ui/BackwardNavigationBar.tsx
  src/widgets/navigationbar/ui/CloseNavigationBar.tsx
  src/widgets/navigationbar/ui/GlobalNavigationBar.tsx
Labels: ⚙️ 환경 설정

#138 [Refactor] 이메일 회원가입 폼 리팩토링
  src/features/auth/api/signUp.ts
  src/features/auth/constants/endpoint.ts
  src/features/auth/lib/validate.ts
  src/features/auth/model/index.ts
  src/features/auth/model/useSignUpByEmailForm.ts
  src/features/auth/store/form.ts
  src/features/auth/ui/SignUpByEmailForm.stories.tsx
  src/features/auth/ui/SignUpByEmailForm.tsx
  src/mocks/handler.ts
  src/shared/ui/input/Input.tsx
  src/shared/ui/input/input.styles.ts
Labels: ⚒️ 리팩토링

#139 [Feat] Region Modal 생성
  src/features/auth/api/region.ts
  src/features/auth/api/signUp.ts
  src/features/auth/constants/endpoint.ts
  src/features/auth/constants/form.ts
  src/features/auth/constants/index.ts
  src/features/auth/constants/message.ts
  src/features/auth/store/form.ts
  src/features/auth/ui/RegionModa.stories.tsx
  src/features/auth/ui/RegionModal.tsx
  src/features/auth/ui/UserInfoRegistrationForm.stories.tsx
  src/features/auth/ui/UserInfoRegistrationForm.tsx
  src/pages/layout.tsx
  src/pages/login/layout.tsx
  src/pages/sign-up/page.tsx
  src/pages/sign-up/pet-info/page.tsx
  src/pages/sign-up/user-info/page.tsx
  src/shared/assets/cancel.svg
  src/shared/assets/search.svg
  src/shared/ui/chip/ActionChip.stories.tsx
  src/shared/ui/chip/ActionChip.tsx
  src/shared/ui/chip/chip.styles.ts
  src/shared/ui/chip/index.ts
  src/shared/ui/icon/index.ts
  src/shared/ui/modal/Modal.styles.ts
  src/shared/ui/navigationbar/BackwardNavigationBar.tsx
  src/shared/ui/navigationbar/CloseNavigationBar.tsx
  src/shared/ui/navigationbar/GlobalNavigationBar.tsx
  src/shared/ui/navigationbar/NavigationBar.stories.tsx
  src/shared/ui/navigationbar/NavigationBar.tsx
  src/shared/ui/navigationbar/index.ts
  src/widgets/navigationbar/ui/index.ts
  src/widgets/navigationbar/ui/navigationbar.stories.tsx
Labels: 👶 기능

#141 [Feat] 기본 정보 입력 폼에서 닉네임 중복 확인 기능 추가
  src/features/auth/api/signUp.ts
  src/features/auth/constants/endpoint.ts
  src/features/auth/store/form.ts
  src/features/auth/ui/UserInfoRegistrationForm.stories.tsx
  src/features/auth/ui/UserInfoRegistrationForm.tsx
  src/mocks/handler.ts
Labels: 👶 기능

#144 [Feat] 이메일 회원가입 페이지에서 이전 페이지로 돌아가는 [<-] 버튼 구현
  src/features/auth/store/form.ts
  src/pages/sign-up/page.tsx
  src/shared/ui/button/Button.tsx
Labels: 👶 기능

#145 [Feat] 회원가입 축하 모달 생성
  public/default-image.png
  public/default-profile.svg
  src/entities/auth/ui/SignUpLandingModal.stories.tsx
  src/entities/auth/ui/SignUpLandingModal.tsx
  src/entities/auth/ui/index.ts
  src/features/auth/ui/PetInfoForm.tsx
  src/features/auth/ui/UserInfoRegistrationForm.stories.tsx
  src/features/auth/ui/UserInfoRegistrationForm.tsx
  src/features/map/ui/GoogleMaps.tsx
  src/pages/map/page.tsx
Labels: 👶 기능

#147 [Hotfix] Full Page 모달 너비 변경
  src/entities/map/ui/Pin.stories.tsx
  src/shared/ui/modal/Modal.styles.ts
Labels: 🐛 버그

#152 [Refactor] /map 페이지 구조 리팩토링
  src/entities/map/ui/FloatingButton.stories.tsx
  src/features/map/ui/index.ts
  src/pages/map/page.tsx
  src/shared/assets/star.svg
  src/shared/ui/icon/index.ts
  src/widgets/map/constants/index.ts
  src/widgets/map/ui/GoogleMaps.tsx
  src/widgets/map/ui/GoogleMapsCopyRight.tsx
  src/widgets/map/ui/MapControlWidget.tsx
  src/widgets/map/ui/MapMarkerWidget.tsx
  src/widgets/map/ui/index.ts
Labels: 👶 기능, ⚒️ 리팩토링, 🐛 버그

#154 [Feat] ImgSlider 컴포넌트 생성
  src/global.css
  src/shared/ui/imgSlider/ImgSlider.stories.tsx
  src/shared/ui/imgSlider/ImgSlider.tsx
  src/shared/ui/imgSlider/index.ts
Labels: 👶 기능

#157 [Feat] useMapStore 생성
  src/features/map/constants/index.ts
  src/features/map/store/index.ts
  src/features/map/store/map.ts
  src/shared/lib/debounce.ts
  src/widgets/map/ui/GoogleMaps.tsx
Labels: 👶 기능

#160 [Hotfix] OverlayPortal 인터렉션 막히는 문제 해결
  src/app/OverlayPortal.tsx
Labels: 🐛 버그

#163 [Chore] 스토리북 CI 환경 생성
  .github/workflows/storybook.yml
Labels: ⚙️ 환경 설정

#168 [Chore] 스토리북 정적 빌드 파일 경로 추가
  .storybook/main.ts
  src/entities/auth/ui/SignUpLandingModal.tsx
  src/entities/map/ui/Pin.stories.tsx
  src/shared/ui/imgSlider/ImgSlider.stories.tsx
  src/widgets/map/ui/GoogleMapsCopyRight.tsx
  src/widgets/map/ui/MapMarkerWidget.tsx
Labels: ⚙️ 환경 설정

#165 [Feat] PetInfoFormData 제출 양식 변경
  src/features/auth/api/petinfo.ts
Labels: 👶 기능

#158 [Feat] edit 모드에서 사용 될 MarkingModal 생성
  .github/workflows/storybook.yml
  src/entities/map/ui/MapSnackbar.tsx
  src/entities/map/ui/Pin.stories.tsx
  src/entities/map/ui/Pin.tsx
  src/features/map/api/form.ts
  src/features/map/api/index.ts
  src/features/map/api/location.ts
  src/features/map/constants/index.ts
  src/features/map/constants/message.ts
  src/features/map/store/form.ts
  src/features/map/store/map.ts
  src/features/map/ui/MapControlButton.tsx
  src/features/map/ui/MapMarkers.tsx
  src/features/map/ui/MarkingButton.tsx
  src/features/map/ui/MarkingFormCloseModal.tsx
  src/features/map/ui/MarkingFormModal.stories.tsx
  src/features/map/ui/MarkingFormModal.tsx
  src/features/map/ui/index.ts
  src/mocks/handler.ts
  src/shared/assets/exit.svg
  src/shared/assets/plus.svg
  src/shared/lib/debounce.ts
  src/shared/lib/index.ts
  src/shared/ui/button/Button.tsx
  src/shared/ui/icon/index.ts
  src/shared/ui/navigationbar/CloseNavigationBar.tsx
  src/shared/ui/navigationbar/NavigationBar.tsx
  src/shared/ui/snackbar/Snackbar.tsx
  src/widgets/map/ui/GoogleMaps.tsx
  src/widgets/map/ui/MapControlWidget.tsx
  src/widgets/map/ui/MapMarkerWidget.tsx
Labels: ⚒️ 리팩토링, 🐛 버그

#172 [Refactor] env 파일에 api url 관리
  .github/workflows/storybook.yml
  .gitignore
  src/features/auth/constants/endpoint.ts
  src/features/map/constants/index.ts
  src/mocks/handler.ts
  src/vite-env.d.ts
Labels: ⚒️ 리팩토링

#174 [Feat] useMapStore mapInfo 상태 롤백
  src/features/map/store/map.ts
  src/shared/lib/debounce.ts
  src/shared/lib/index.ts
  src/widgets/map/ui/GoogleMaps.tsx
Labels: 👶 기능

#176 [Feat] 내 위치 기반 지도 이동 기능 추가
  src/features/auth/ui/RegionModal.tsx
  src/features/map/store/map.ts
  src/features/map/ui/MapControlButton.tsx
  src/features/map/ui/MapMarkers.tsx
  src/widgets/map/ui/GoogleMaps.tsx
Labels: 👶 기능

#183 [Feat] PetInfoForm dogBreed 리스트 업데이트
  src/features/auth/constants/form.ts
Labels: 👶 기능

#182 [Refactor] render props 패턴을 이용하여 App 레이어 리팩토링
  src/app/index.ts
  src/app/layout/GlobalNavigationBar.tsx
  src/app/layout/MainFooter.stories.tsx
  src/app/layout/MainFooter.style.ts
  src/app/layout/MainFooter.tsx
  src/app/layout/index.ts
  src/app/router.tsx
  src/features/map/ui/MarkingFormModal.stories.tsx
  src/pages/layout.tsx
  src/pages/login/layout.tsx
  src/pages/map/page.tsx
  src/pages/page.tsx
  src/shared/ui/navigationbar/NavigationBar.stories.tsx
  src/shared/ui/navigationbar/index.ts
  src/widgets/map/ui/index.ts
Labels: ⚒️ 리팩토링

#188 [Feat] DividerLine 컴포넌트 생성
  src/shared/ui/divider/DividerLine.stories.tsx
  src/shared/ui/divider/DividerLine.tsx
  src/shared/ui/divider/index.ts
Labels: 👶 기능

#185 [Feat] MyPage UI 퍼블리싱
  src/app/layout/MainFooter.stories.tsx
  src/app/layout/MainFooter.tsx
  src/app/router.tsx
  src/entities/profile/ui/GalleryGrid.tsx
  src/entities/profile/ui/ProfileOverview.tsx
  src/entities/profile/ui/TemporaryMarkingBar.tsx
  src/entities/profile/ui/index.ts
  src/pages/my-page/index.ts
  src/pages/my-page/myPage.stories.tsx
  src/pages/my-page/page.tsx
  src/shared/assets/arrow-right.svg
  src/shared/assets/compass.svg
  src/shared/assets/drop-down.svg
  src/shared/assets/info.svg
  src/shared/assets/setting.svg
  src/shared/ui/chip/InfoChip.stories.tsx
  src/shared/ui/chip/InfoChip.tsx
  src/shared/ui/chip/chip.styles.ts
  src/shared/ui/icon/index.ts
  src/shared/ui/navigationbar/index.ts
  src/widgets/profile/ui/ProfileNavigationBar.stories.tsx
  src/widgets/profile/ui/ProfileNavigationBar.tsx
  src/widgets/profile/ui/ProfileOverView.stories.tsx
  src/widgets/profile/ui/ProfileOverView.tsx
  src/widgets/profile/ui/index.ts
Labels: 👶 기능

#190 [Feat] /my-page/setting 퍼블리싱
  src/app/router.tsx
  src/entities/setting/ui/VersionInfo.tsx
  src/entities/setting/ui/index.ts
  src/features/setting/ui/AccountManagement.tsx
  src/features/setting/ui/EditMyInfo.tsx
  src/features/setting/ui/LogoutButton.tsx
  src/features/setting/ui/MyActivity.tsx
  src/features/setting/ui/Notification.tsx
  src/features/setting/ui/Report.tsx
  src/features/setting/ui/TermOfService.tsx
  src/features/setting/ui/_LogoutModal.tsx
  src/features/setting/ui/index.ts
  src/features/setting/ui/setting.styles.ts
  src/pages/my-page/setting/SettingPage.stories.tsx
  src/pages/my-page/setting/index.ts
  src/pages/my-page/setting/page.tsx
  src/shared/assets/arrow-right.svg
  src/shared/constants/index.ts
  src/shared/ui/navigationbar/BackwardNavigationBar.tsx
  src/widgets/profile/ui/ProfileNavigationBar.tsx
Labels: 👶 기능

#196 [Chore] 개발 환경에서 사용 할 DevTools 컴포넌트 생성
  src/app/DevToolst.tsx
  src/main.tsx
  src/shared/store/auth.ts
  src/vite-env.d.ts
Labels: ⚙️ 환경 설정

#192 [Feat] ConfirmModal 생성
  src/shared/ui/modal/ConfirmModal.stories.tsx
  src/shared/ui/modal/ConfirmModal.tsx
  src/shared/ui/modal/index.ts
Labels: 👶 기능

#202 [Hotfix] my-page/setting 에서 라우팅 처리 하기
  src/features/setting/ui/_LogoutModal.tsx
  src/pages/my-page/setting/page.tsx
Labels: 🐛 버그

#189 [Feat] map 페이지의 url에 따라 map store 변경
  src/entities/map/ui/CurrentLocationLoading.tsx
  src/entities/map/ui/index.ts
  src/features/map/lib/index.ts
  src/features/map/lib/useCurrentLocation.ts
  src/features/map/store/map.ts
  src/features/map/ui/MapControlButton.tsx
  src/features/map/ui/MapMarkers.tsx
  src/pages/map/page.tsx
  src/shared/assets/reset.svg
  src/shared/ui/icon/index.ts
  src/widgets/map/ui/GoogleMaps.tsx
  src/widgets/map/ui/MapInitializer.tsx
  src/widgets/map/ui/index.ts
Labels: 👶 기능

#207 [Hotfix] input file 을 제거해도 업데이트가 되지 않는 버그 수정
  src/features/auth/ui/PetInfoForm.tsx
  src/features/map/ui/MarkingFormModal.tsx
Labels: 🐛 버그

#208 [Feat] 마킹을 보여주는 MarkingItem 컴포넌트 생성
  src/entities/marking/ui/MarkingList.tsx
  src/entities/marking/ui/index.ts
  src/features/marking/api/index.ts
  src/features/marking/api/search.ts
  src/features/marking/contants/index.ts
  src/features/marking/contants/requestUrl.ts
  src/features/marking/ui/MarkingItem.stories.tsx
  src/features/marking/ui/MarkingItem.tsx
  src/features/marking/ui/index.ts
  src/global.css
  src/mocks/data/markingList.json
  src/mocks/handler.ts
  src/shared/assets/bookmark.svg
  src/shared/assets/filled-bookmark.svg
  src/shared/assets/filled-like.svg
  src/shared/assets/like.svg
  src/shared/assets/more.svg
  src/shared/ui/icon/index.ts
  src/shared/ui/imgSlider/ImgSlider.tsx
Labels: 👶 기능

#203 [Feat] /my-page/setting/manage-account 퍼블리싱 생성
  src/app/router.tsx
  src/entities/profile/ui/ProfileOverview.tsx
  src/entities/setting/ui/Account.tsx
  src/entities/setting/ui/VersionInfo.tsx
  src/entities/setting/ui/index.ts
  src/entities/setting/ui/setting.styles.ts
  src/features/setting/lib/account.tsx
  src/features/setting/lib/index.ts
  src/features/setting/store/account.ts
  src/features/setting/store/index.ts
  src/features/setting/ui/Account.tsx
  src/features/setting/ui/AccountManagement.tsx
  src/features/setting/ui/_AccountCancellactionModal.stories.tsx
  src/features/setting/ui/_AccountCancellationModal.tsx
  src/features/setting/ui/_CancellationCheckModal.tsx
  src/features/setting/ui/_CancellcationCheckModal.stories.tsx
  src/features/setting/ui/_PasswordChangeModal.stories.tsx
  src/features/setting/ui/_PasswordChangeModal.tsx
  src/features/setting/ui/index.ts
  src/pages/my-page/setting/manage-account/index.ts
  src/pages/my-page/setting/manage-account/page.tsx
  src/shared/constants/index.ts
  src/shared/lib/overlay.ts
  src/shared/store/overlay.ts
  src/shared/ui/modal/ConfirmModal.tsx
  src/shared/ui/modal/ExitConfirmModal.stories.tsx
  src/shared/ui/modal/ExitConfirmModal.tsx
  src/shared/ui/modal/index.ts
  src/shared/ui/notice/Notice.stories.tsx
  src/shared/ui/notice/Notice.tsx
  src/shared/ui/notice/index.ts
Labels: 👶 기능

#210 [Hotfix] Image Blink 현상 버그 픽스
  src/features/auth/ui/PetInfoForm.tsx
  src/features/map/ui/MarkingFormModal.tsx
Labels: 🐛 버그

#214 [Feat] [현 지도에서 재검색] 버튼 구현
  src/features/map/lib/index.ts
  src/features/map/lib/useResearchMarkingList.ts
  src/features/map/store/map.ts
  src/features/map/ui/MapMarkers.tsx
  src/features/map/ui/MarkingResearchButton.tsx
  src/features/map/ui/index.ts
  src/features/marking/api/search.ts
  src/features/marking/contants/requestUrl.ts
  src/widgets/map/ui/GoogleMaps.tsx
  src/widgets/map/ui/MapControlWidget.tsx
  src/widgets/map/ui/MapInitializer.tsx
Labels: 👶 기능
