Repository dogandme/frontend, pull requests merged in 2024-12, with the labels that each got.

#512 [Hotfix] 스켈레톤 페이지 네비게이션 수정 사항 적용 , 스타일 롤백
  src/pages/[nickname]/follower/page.tsx
  src/pages/[nickname]/following/page.tsx
  src/pages/[nickname]/loading.tsx
  src/pages/[nickname]/marking/page.tsx
  src/pages/setting/edit-info/page.tsx
  src/pages/setting/manage-account/page.tsx
  src/pages/temporary-marking/page.tsx
  src/shared/ui/navigationBar/NavigationBar.tsx
Labels: 👶 기능, 🐛 버그

#515 [Feat] 이미지 로딩 기능 추가 및 적용
  public/failed_image.svg
  src/app/FooterNavigationBar.tsx
  src/entities/marking/api/getDashboardMarkingThumbnail.ts
  src/entities/marking/api/getMarkingDetail.ts
  src/entities/marking/api/getMarkingList.ts
  src/entities/marking/api/getMyLikedMarkingList.ts
  src/entities/marking/api/getMySavedMarkerList.ts
  src/entities/profile/ui/dashboard.tsx
  src/entities/profile/ui/index.ts
  src/entities/profile/ui/profileImage.tsx
  src/shared/lib/image.ts
  src/shared/ui/imgSlider/ImgSlider.tsx
  src/widgets/follow/followerUserItem.tsx
  src/widgets/follow/followingUserItem.tsx
  src/widgets/map/ui/localMarkingListBottomSheet.tsx
  src/widgets/marking/ui/markingItem.tsx
  src/widgets/marking/ui/markingThumbnailGrid.tsx
  src/widgets/profile/ui/myProfileOverview.tsx
  src/widgets/profile/ui/profileOverview.tsx
Labels: 👶 기능

#518 [Feat] 500에러와 알 수 없는 에러 처리
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/pages/errorBoundary.tsx
  src/pages/serverError.tsx
  src/pages/unknownError.tsx
Labels: 👶 기능

#522 [Hotfix] 로드 할 이미지가 없는 경우 use .. ImageState 의 로딩 상태가 변경되지 않던 버그 수정
  src/shared/lib/image.ts
Labels: 🐛 버그

#528 [Fix] 잘못된 import 경로 수정
  src/entities/auth/assets/index.ts
  src/entities/auth/ui/input.tsx
  src/entities/profile/ui/dashboard.tsx
  src/features/follow/ui/followingToggle.tsx
  src/shared/ui/button/button.stories.tsx
  src/shared/ui/button/button.tsx
  src/shared/ui/button/index.ts
  src/shared/ui/checkbox/checkbox.stories.tsx
  src/shared/ui/chip/index.ts
  src/shared/ui/icon/index.ts
  src/shared/ui/modal/modal.tsx
  src/widgets/marking/ui/temporaryMarkingItem.tsx
  src/widgets/profile/ui/profileOverview.tsx
Labels: ⚒️ 리팩토링, 🐛 버그

#533 [Hotfix] 스낵바 생명주기를 호출한 컴포넌트의 생명주기와 상관 없도록 변경
  src/app/AppProviderLayout.tsx
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/app/SnackbarController.tsx
  src/features/auth/api/postSendCode.ts
  src/features/auth/ui/changeNicknameModal.tsx
  src/features/auth/ui/loginForm.tsx
  src/features/auth/ui/petInformationForm.stories.tsx
  src/features/auth/ui/petInformationForm.tsx
  src/features/auth/ui/regionModal.tsx
  src/features/auth/ui/signUpByEmailForm.stories.tsx
  src/features/auth/ui/signUpByEmailForm.tsx
  src/features/auth/ui/userInfoRegistrationForm.stories.tsx
  src/features/auth/ui/userInfoRegistrationForm.tsx
  src/features/map/hooks/useCurrentLocation.ts
  src/features/map/ui/mapControlButton.tsx
  src/features/marking/api/postAddMarking.tsx
  src/features/marking/api/postAddTempMarking.tsx
  src/features/marking/ui/editMarkingFormModal.tsx
  src/features/marking/ui/markingFormModal.stories.tsx
  src/features/marking/ui/markingFormModal.tsx
  src/features/setting/api/putChangePassword.ts
  src/features/setting/api/putSetPassword.ts
  src/features/setting/ui/logoutModal.tsx
  src/features/setting/ui/passwordChangeModal.tsx
  src/features/setting/ui/setting.tsx
  src/pages/setting/page.tsx
  src/shared/lib/index.ts
  src/shared/lib/snackbar.tsx
  src/shared/store/index.ts
  src/shared/store/overlay.ts
  src/shared/store/snackbar.ts
  src/shared/ui/snackbar/snackbar.stories.tsx
  src/widgets/map/ui/mapInitializer.tsx
  src/widgets/marking/ui/markingItem.tsx
Labels: 🐛 버그

#532 [Refactor] 이메일 회원가입 테스트 코드 수정
  src/features/auth/ui/signUpByEmailForm.stories.tsx
  src/features/auth/ui/signUpByEmailForm.tsx
Labels: ⚒️ 리팩토링

#537 [Refactor] msw handler 리팩토링
  src/features/auth/ui/loginForm.stories.tsx
  src/features/auth/ui/petInformationForm.stories.tsx
  src/features/auth/ui/regionModal.stories.tsx
  src/features/auth/ui/signUpByEmailForm.stories.tsx
  src/features/auth/ui/userInfoRegistrationForm.stories.tsx
  src/features/marking/ui/markingFormModal.stories.tsx
  src/mocks/handler.ts
  src/mocks/handlers/auth.ts
  src/mocks/handlers/follow.ts
  src/mocks/handlers/map.ts
  src/mocks/handlers/marking.ts
  src/mocks/handlers/profile.ts
  src/mocks/handlers/setting.ts
  src/widgets/marking/ui/markingItem.stories.tsx
Labels: ⚒️ 리팩토링

#539 [Hotfix] SnackbarController 내부 removeOverlay를 setSnackbarProps 내부로 이동
  src/app/SnackbarController.tsx
  src/shared/store/snackbar.ts
Labels: 🐛 버그

#541 [Feat] 라우터 페이지 레이지 로딩 처리
  src/app/router.tsx
  src/pages/[nickname]/follower/index.ts
  src/pages/[nickname]/follower/page.tsx
  src/pages/[nickname]/following/index.ts
  src/pages/[nickname]/following/page.tsx
  src/pages/[nickname]/index.ts
  src/pages/[nickname]/marking/index.ts
  src/pages/[nickname]/marking/page.tsx
  src/pages/[nickname]/notFoundUser.tsx
  src/pages/[nickname]/page.tsx
  src/pages/index.ts
  src/pages/login/email/index.ts
  src/pages/map/index.ts
  src/pages/map/layout.tsx
  src/pages/map/my/index.ts
  src/pages/map/my/page.tsx
  src/pages/map/page.tsx
  src/pages/map/place/index.ts
  src/pages/map/place/page.tsx
  src/pages/setting/edit-info/index.ts
  src/pages/setting/edit-info/page.tsx
  src/pages/setting/index.ts
  src/pages/setting/manage-account/index.ts
  src/pages/setting/manage-account/page.tsx
  src/pages/setting/page.tsx
  src/pages/setting/settingPage.stories.tsx
  src/pages/sign-up/index.ts
  src/pages/sign-up/pet-info/index.ts
  src/pages/sign-up/user-info/index.ts
  src/pages/temporary-marking/index.ts
  src/pages/temporary-marking/page.tsx
  src/shared/lib/image.ts
  src/widgets/map/ui/index.ts
  src/widgets/map/ui/myActivityList.tsx
Labels: 👶 기능

#546 [Feat] favicon과 meta 태그 설정
  index.html
  public/apple-touch-icon.png
  public/favicon-96x96.png
  public/favicon.ico
  public/favicon.svg
  public/mung-with-me.png
  public/site.webmanifest
  public/web-app-manifest-192x192.png
  public/web-app-manifest-512x512.png
  src/pages/map/layout.tsx
Labels: 👶 기능

#544 [Hotfix] 스낵바 컨트롤러 언마운트 후에 snackbarProps 상태가 유지되던 문제 해결
  src/app/SnackbarController.tsx
  src/shared/store/snackbar.ts
Labels: 🐛 버그

#547 [Refactor] putAddUserRegistration ... 의 body값에서 토큰 제거
  src/features/auth/api/putAddUserInfo.ts
Labels: ⚒️ 리팩토링

#550 [Refactor] putUserInfoRegistration의 token 인수 삭제
  src/features/auth/ui/userInfoRegistrationForm.tsx
Labels: ⚒️ 리팩토링, 🐛 버그

#549 [Feat] useGetMyProfile staleTime infinity 로 변경
  src/app/FooterNavigationBar.tsx
  src/entities/profile/api/getProfile.ts
  src/entities/profile/api/queryKey.ts
  src/features/follow/api/deleteFollowing.ts
  src/features/follow/api/postFollowing.ts
  src/features/marking/api/deleteLikeMarking.ts
  src/features/marking/api/deleteSavedMarking.ts
  src/features/marking/api/deleteTemporaryMarking.ts
  src/features/marking/api/postAddTempMarking.tsx
  src/features/marking/api/postLikeMarking.ts
  src/features/marking/api/postSaveMarking.ts
  src/features/marking/api/putModifyMarking.ts
  src/features/setting/api/putChangePetInfo.ts
  src/pages/[nickname]/myProfilePage.tsx
  src/widgets/map/ui/myMarkingListBottomSheet.tsx
Labels: 👶 기능, ⚒️ 리팩토링

#552 [Refactor] queryKey의 all 값 수정
  src/entities/map/api/queryKey.ts
  src/entities/marking/api/queryKey.ts
  src/entities/profile/api/queryKey.ts
Labels: ⚒️ 리팩토링

#553 [Refactor] 로그인에서 persistLogin 제거
  src/features/auth/api/postLogin.ts
  src/features/auth/store/form.ts
  src/features/auth/ui/loginForm.stories.tsx
  src/features/auth/ui/loginForm.tsx
  src/pages/login/email/page.tsx
Labels: 👶 기능

#557 [Refactor] input 컴포넌트 props에서 statusText 삭제
  src/entities/auth/ui/input.stories.tsx
  src/entities/auth/ui/input.tsx
  src/features/auth/ui/loginForm.tsx
  src/features/auth/ui/nicknameInput.tsx
  src/features/auth/ui/petInformationForm.tsx
  src/features/auth/ui/signUpByEmailForm.tsx
  src/features/setting/ui/passwordChangeModal.tsx
  src/features/setting/ui/passwordCheckModal.tsx
  src/features/setting/ui/passwordSetModal.tsx
  src/shared/ui/input/input.stories.tsx
  src/shared/ui/input/input.tsx
Labels: ⚒️ 리팩토링

#556 [Refactor] useOverlay , useModal , useSnackbar 리팩토링
  src/app/AppProviderLayout.tsx
  src/app/OverlayPortal.tsx
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/app/SnackbarController.tsx
  src/features/auth/api/postSendCode.ts
  src/features/auth/ui/changeNicknameModal.tsx
  src/features/auth/ui/loginForm.tsx
  src/features/auth/ui/petInformationForm.stories.tsx
  src/features/auth/ui/petInformationForm.tsx
  src/features/auth/ui/regionModal.tsx
  src/features/auth/ui/signUpByEmailForm.stories.tsx
  src/features/auth/ui/signUpByEmailForm.tsx
  src/features/auth/ui/userInfoRegistrationForm.stories.tsx
  src/features/auth/ui/userInfoRegistrationForm.tsx
  src/features/map/hooks/useCurrentLocation.ts
  src/features/map/ui/mapControlButton.tsx
  src/features/marking/api/postAddMarking.tsx
  src/features/marking/api/postAddTempMarking.tsx
  src/features/marking/lib/markingModal.ts
  src/features/marking/ui/editMarkingFormModal.tsx
  src/features/marking/ui/markingFormModal.stories.tsx
  src/features/marking/ui/markingFormModal.tsx
  src/features/setting/api/putChangePassword.ts
  src/features/setting/api/putSetPassword.ts
  src/features/setting/ui/logoutModal.tsx
  src/features/setting/ui/passwordChangeModal.tsx
  src/features/setting/ui/setting.tsx
  src/global.css
  src/pages/setting/page.tsx
  src/pages/sign-up/page.tsx
  src/shared/constants/index.ts
  src/shared/lib/index.ts
  src/shared/lib/modal.ts
  src/shared/lib/overlay.tsx
  src/shared/store/index.ts
  src/shared/store/snackbar.ts
  src/shared/store/snackbar.tsx
  src/shared/ui/modal/confirmModal.stories.tsx
  src/shared/ui/modal/confirmModal.tsx
  src/shared/ui/modal/index.ts
  src/shared/ui/modal/modal.stories.tsx
  src/shared/ui/overlay/overlay.mock.tsx
  src/shared/ui/overlay/overlay.stories.tsx
  src/shared/ui/snackbar/snackbar.stories.tsx
  src/shared/ui/snackbar/snackbar.tsx
  src/widgets/map/ui/mapInitializer.tsx
  src/widgets/marking/ui/markingItem.tsx
Labels: 👶 기능, ⚒️ 리팩토링

#562 [Refactor] Input 최상단 요소 width를 100%로 설정
  src/shared/ui/input/input.tsx
Labels: 🐛 버그

#561 [Hotfix] 모달을 감싸는 OverlayWrapper 스타일 버그 수정
  src/app/OverlayPortal.tsx
Labels: 🐛 버그
