Repository dogandme/frontend, pull requests merged in 2024-10, with the labels that each got.

#223 [Feat] 맵 바텀 시트 생성
  src/app/layout/MainFooter.tsx
  src/entities/map/ui/FloatingButton.stories.tsx
  src/entities/map/ui/FloatingButton.styles.ts
  src/entities/map/ui/FloatingButton.tsx
  src/entities/map/ui/index.ts
  src/features/map/ui/MapControlButton.tsx
  src/features/marking/ui/MarkingItem.stories.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/shared/assets/dog-foot.svg
  src/shared/ui/button/Button.tsx
  src/shared/ui/icon/index.ts
  src/widgets/map/ui/MapControlWidget.tsx
Labels: 👶 기능

#230 [Refactor] marking과 관련된 컴포넌트 리팩토링
  src/entities/marking/ui/index.ts
  src/entities/marking/ui/markingList.tsx
  src/features/map/ui/MapControlButton.tsx
  src/features/map/ui/index.ts
  src/features/marking/store/index.ts
  src/features/marking/store/markingForm.ts
  src/features/marking/ui/index.ts
  src/features/marking/ui/markingFormCloseModal.tsx
  src/features/marking/ui/markingFormModal.stories.tsx
  src/features/marking/ui/markingFormModal.tsx
  src/features/marking/ui/markingItem.stories.tsx
  src/features/marking/ui/markingItem.tsx
Labels: ⚒️ 리팩토링

#233 [Refactor] map 도메인 리팩토링
  src/entities/map/ui/currentLocationLoading.tsx
  src/entities/map/ui/customMarker.tsx
  src/entities/map/ui/index.ts
  src/entities/map/ui/mapSnackBar.tsx
  src/entities/map/ui/mapSnackbar.tsx
  src/entities/map/ui/pin.stories.tsx
  src/entities/map/ui/pin.tsx
  src/features/map/api/form.ts
  src/features/map/constants/index.ts
  src/features/map/constants/message.ts
  src/features/map/hooks/index.ts
  src/features/map/hooks/useCurrentLocation.ts
  src/features/map/hooks/useResearchMarkingList.ts
  src/features/map/ui/index.ts
  src/features/map/ui/mapControlButton.tsx
  src/features/map/ui/mapMarkers.tsx
  src/features/map/ui/markingResearchButton.tsx
  src/features/marking/api/addMarking.ts
  src/features/marking/api/addTempMarking.ts
  src/features/marking/api/index.ts
  src/features/marking/api/search.ts
  src/features/marking/constants/index.ts
  src/features/marking/constants/message.ts
  src/features/marking/constants/requestUrl.ts
  src/features/marking/contants/index.ts
  src/features/marking/store/markingForm.ts
  src/features/marking/ui/markingFormModal.tsx
  src/features/marking/ui/markingItem.tsx
  src/mocks/handler.ts
  src/pages/map/page.tsx
  src/widgets/map/ui/googleMaps.tsx
  src/widgets/map/ui/googleMapsCopyRight.tsx
  src/widgets/map/ui/index.ts
  src/widgets/map/ui/mapControlWidget.tsx
  src/widgets/map/ui/mapInitializer.tsx
  src/widgets/map/ui/mapMarkerWidget.tsx
Labels: ⚒️ 리팩토링

#234 [Refactor] mutationOption 을 useMutation 훅 내부로 이동
  .storybook/preview.tsx
  src/features/auth/api/login.ts
  src/features/auth/api/petinfo.ts
  src/features/auth/api/signUp.ts
  src/features/auth/ui/LoginForm.stories.tsx
  src/features/auth/ui/LoginForm.tsx
  src/features/auth/ui/PetInfoForm.tsx
  src/features/auth/ui/SignUpByEmailForm.tsx
  src/features/auth/ui/UserInfoRegistrationForm.tsx
  src/features/marking/api/addMarking.ts
  src/features/marking/api/addTempMarking.ts
  src/features/marking/ui/markingFormModal.tsx
  src/mocks/handler.ts
Labels: ⚒️ 리팩토링

#244 [Feat] 디자인 변경에 따른 Age 바텀 시트 내용 변경
  src/features/auth/api/signUp.ts
  src/features/auth/constants/form.ts
  src/features/auth/store/form.ts
  src/mocks/handler.ts
Labels: 👶 기능

#243 [Feat] Logout 기능 생성하고 로그아웃 모달에 기능 추가 하기
  src/features/setting/api/index.ts
  src/features/setting/api/postLogout.ts
  src/features/setting/constants/endpoint.ts
  src/features/setting/constants/index.ts
  src/features/setting/ui/logoutModal.tsx
  src/mocks/handler.ts
  src/shared/store/auth.ts
Labels: 👶 기능

#246 [Refactor] MarkingItem 좋아요/저장/삭제 기능 추가
  src/app/layout/MainFooter.tsx
  src/features/auth/ui/RegionModal.tsx
  src/features/marking/api/deleteMarking.ts
  src/features/marking/api/getMarkingList.ts
  src/features/marking/api/index.ts
  src/features/marking/api/likeMarking.ts
  src/features/marking/api/postMarkingForm.ts
  src/features/marking/api/postTempMarkingForm.ts
  src/features/marking/api/saveMarking.ts
  src/features/marking/constants/requestUrl.ts
  src/features/marking/ui/markingItem.stories.tsx
  src/features/marking/ui/markingItem.tsx
  src/mocks/handler.ts
  src/shared/ui/list/List.tsx
Labels: 👶 기능

#256 [Hotfix] postLogout 백엔드 요구 사항에 맞춰 기능 수정
  src/features/setting/api/postLogout.ts
Labels: 🐛 버그

#254 [Hotfix] postPetInfoForm 백엔드 요구 사항에 맞춰 기능 변경
  src/features/auth/api/index.ts
  src/features/auth/api/postPetInfo.ts
  src/features/auth/ui/PetInfoForm.tsx
  src/mocks/handler.ts
Labels: ⚒️ 리팩토링, 🐛 버그

#249 [Feat] GET 요청에 대한 accessToken , refreshToken 재발급 로직 생성
  .storybook/preview.tsx
  src/app/DevTools.tsx
  src/app/ReactQueryProvider/ReactQueryProvider.tsx
  src/app/ReactQueryProvider/constants.ts
  src/app/ReactQueryProvider/errorHandlers.ts
  src/app/ReactQueryProvider/index.ts
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/app/index.ts
  src/app/layout/MainFooter.tsx
  src/entities/profile/api/dashboard.ts
  src/entities/profile/ui/dashboard.tsx
  src/features/auth/api/postPetInfo.ts
  src/features/auth/ui/PetInfoForm.stories.tsx
  src/features/auth/ui/hyperlinks.tsx
  src/mocks/handler.ts
  src/pages/my-page/page.tsx
Labels: 👶 기능, 🐛 버그

#266 [Refactor] api base url 상수 생성
  src/app/ReactQueryProvider/constants.ts
  src/app/layout/MainFooter.tsx
  src/entities/marking/ui/dashboard.tsx
  src/entities/profile/constants/endpoint.ts
  src/entities/profile/ui/dashboard.tsx
  src/features/auth/constants/endpoint.ts
  src/features/map/constants/index.ts
  src/features/marking/constants/requestUrl.ts
  src/features/marking/ui/markingItem.tsx
  src/features/setting/constants/endpoint.ts
  src/mocks/handler.ts
  src/shared/constants/index.ts
Labels: ⚒️ 리팩토링

#267 [Feat] Mutation에 대한 Access Token 재발급 에러 핸들링 로직 추가
  src/app/ReactQueryProvider/errorHandlers.ts
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/mocks/handler.ts
Labels: 👶 기능

#269 [Refactor] Router 단일 루트 트리 구조로 변경
  src/app/AppProviderLayout.tsx
  src/app/FooterNavigationBar.stories.tsx
  src/app/FooterNavigationBar.tsx
  src/app/MainLayout.tsx
  src/app/MobileLayout.tsx
  src/app/index.ts
  src/app/layout/MainFooter.style.ts
  src/app/layout/index.ts
  src/app/router.tsx
  src/features/marking/ui/markingFormModal.stories.tsx
  src/main.tsx
  src/pages/index.ts
  src/pages/layout.tsx
  src/pages/login/email/email.stories.tsx
  src/pages/login/layout.tsx
  src/pages/map/page.tsx
  src/pages/my-page/page.tsx
  src/pages/my-page/setting/SettingPage.stories.tsx
  src/pages/my-page/setting/page.tsx
  src/pages/page.tsx
  src/shared/constants/index.ts
  src/shared/ui/modal/ConfirmModal.stories.tsx
  src/widgets/notification/ui/NotificationNavigationBar.tsx
  src/widgets/notification/ui/index.ts
Labels: ⚒️ 리팩토링

#276 [Hotfix] AppProvider 구조 올바르게 변경
  src/app/AppProviderLayout.tsx
  src/app/MainLayout.tsx
Labels: 🐛 버그

#271 [Feat] 이메일 회원가입 페이지에서 인증 코드 전송 기능 구현
  src/features/auth/api/signUp.ts
  src/features/auth/store/form.ts
  src/features/auth/ui/SignUpByEmailForm.stories.tsx
  src/features/auth/ui/SignUpByEmailForm.tsx
  src/pages/sign-up/page.tsx
Labels: 👶 기능

#277 [Feat] RefreshToken 만료 시 로그아웃 후 login 페이지로 라우팅 기능 추가
  .storybook/preview.tsx
  src/app/ReactQueryProvider/errorHandlers.ts
  src/app/ReactQueryProvider/useCreateQueryClient.ts
Labels: 👶 기능

#259 [Hotfix] RegionModal UI 디자인 시스템에 맞게 변경
  src/features/auth/store/form.ts
  src/features/auth/ui/RegionModal.tsx
  src/mocks/data/regionList.json
  src/mocks/handler.ts
Labels: ⚒️ 리팩토링, 🐛 버그

#282 [Feat] useGetProfile 타입 수정 및 placeholderData 추가
  src/entities/profile/api/getProfile.ts
  src/entities/profile/api/index.ts
Labels: 👶 기능, ⚒️ 리팩토링

#285 [Refactor] Modal 컴파운트 패턴으로 리팩토링
  src/entities/auth/ui/SignUpLandingModal.tsx
  src/features/auth/ui/UserInfoRegistrationForm.stories.tsx
  src/features/marking/ui/markingFormModal.stories.tsx
  src/features/setting/hooks/usePasswordChangeModal.tsx.tsx
  src/features/setting/hooks/usePasswordCheckModal.tsx.tsx
  src/shared/ui/button/Button.tsx
  src/shared/ui/modal/ExitConfirmModal.stories.tsx
  src/shared/ui/modal/ExitConfirmModal.tsx
  src/shared/ui/modal/Modal.styles.ts
  src/shared/ui/modal/Modal.tsx
  src/shared/ui/modal/index.ts
  src/shared/ui/overlay/overlay.mock.tsx
  src/shared/ui/overlay/overlay.stories.tsx
Labels: ⚒️ 리팩토링

#286 [Feat] 내 정보 요청하는 api 커스텀 훅 생성
  src/entities/auth/api/getMyInfo.ts
  src/entities/auth/api/index.ts
  src/entities/auth/constants/index.ts
  src/features/auth/api/postPetInfo.ts
  src/features/auth/api/signUp.ts
  src/mocks/data/myInfo.json
  src/mocks/handler.ts
  src/pages/my-page/setting/manage-account/page.tsx
Labels: 👶 기능

#289 [Hotfix] Modal.Button에서 충돌 일으키는 클래스 제거
  src/shared/ui/modal/Modal.tsx
Labels: 🐛 버그

#273 [Feat] 서버로 제출하는 Image 용량 압축하여 제출 기능 추가
  src/features/auth/constants/form.ts
  src/features/auth/store/form.ts
  src/features/auth/ui/PetInfoForm.stories.tsx
  src/features/auth/ui/PetInfoForm.tsx
  src/features/marking/constants/index.ts
  src/features/marking/store/markingForm.ts
  src/features/marking/ui/markingFormModal.stories.tsx
  src/features/marking/ui/markingFormModal.tsx
  src/shared/lib/image.ts
  src/shared/lib/index.ts
Labels: 👶 기능, ⚒️ 리팩토링

#297 [Hotfix] Modal.Footer 의 axis 에 따라 버튼의 클래스 명을 동적으로 변경하도록 수정
  src/shared/ui/modal/Modal.mocks.tsx
  src/shared/ui/modal/Modal.tsx
Labels: 🐛 버그

#298 [Feat] 내 정보 수정 페이지 ui
  src/app/router.tsx
  src/mocks/data/myInfo.json
  src/pages/my-page/setting/edit-info/index.ts
  src/pages/my-page/setting/edit-info/page.tsx
  src/pages/my-page/setting/page.tsx
  src/shared/constants/index.ts
Labels: 👶 기능

#300 [Feat] query , mutation 테스트를 위한 핸들러 내부 가상 DB 생성
  src/mocks/data/myInfo.json
  src/mocks/handler.ts
Labels: 👶 기능, ✅ 테스트

#305 [Feat] Modal.Footer 에서 클래스명 받도록 확장
  src/shared/ui/modal/Modal.tsx
Labels: 👶 기능

#308 [Refactor] 사용하지 않는 파일 import 문 제거
  src/shared/ui/bottomSheet/BottomSheet.stories.tsx
Labels: ⚒️ 리팩토링

#312 [Chore] 깃허브 액션 캐싱 스텝 제거
  .github/workflows/storybook.yml
Labels: ⚙️ 환경 설정

#311 [Feat] hyperlink Link 컴포넌트에서 a 태그로 변경
  src/features/auth/ui/hyperlinks.tsx
Labels: 👶 기능, 🐛 버그

#314 [Hotfix] 닉네임 중복 검사 시 토큰 함께 보내도록 API 요청 수정
  src/features/auth/api/signUp.ts
  src/features/auth/ui/UserInfoRegistrationForm.tsx
Labels: 🐛 버그

#315 [Refactor] 이미지 경로 수정
  src/entities/marking/ui/dashboard.tsx
  src/entities/profile/ui/dashboard.tsx
  src/features/map/ui/mapControlButton.tsx
  src/features/map/ui/mapMarkers.tsx
  src/features/marking/ui/markingItem.tsx
Labels: ⚒️ 리팩토링

#317 [Feat] 마킹 모달 서버 요구 사항에 맞춰 기능 변경
  src/features/marking/api/postMarkingForm.ts
  src/features/marking/api/postTempMarkingForm.ts
  src/features/marking/store/markingForm.ts
  src/features/marking/ui/markingFormModal.stories.tsx
  src/features/marking/ui/markingFormModal.tsx
Labels: 👶 기능

#319 [Feat] petInfoForm이미지 없을 경우 멀티파트 폼에서 이미지 제출 하지 않도록 수정
  src/features/auth/api/postPetInfo.ts
Labels: 👶 기능

#321 [Feat] 유저 개인 정보 제출 시 리프레쉬 토큰 함께 전송하도록 기능 수정
  src/features/auth/api/signUp.ts
Labels: 👶 기능

#326 [Hotfix] 이미지 삭제 되지 않는 문제 해결 & 마킹 모달 폼에서 이미지 압축 되지 않는 문제 해결
  src/features/auth/store/form.ts
  src/features/marking/store/markingForm.ts
Labels: ⚒️ 리팩토링, 🐛 버그

#329 [Hotfix] mutationCached 에서 throw error 문 제거
  src/app/ReactQueryProvider/useCreateQueryClient.ts
Labels: 🐛 버그

#331 [Feat] 회원 가입 단계에서 유저 정보에서 성별 선택 안함 필드 추가
  src/features/auth/api/signUp.ts
  src/features/auth/constants/form.ts
  src/features/auth/store/form.ts
Labels: 👶 기능

#327 [Feat] 닉네임 변경 기능
  src/features/auth/api/index.ts
  src/features/auth/api/putChangeNickname.ts
  src/features/auth/api/signUp.ts
  src/features/auth/constants/endpoint.ts
  src/features/auth/ui/ChangeNicknameModal.tsx
  src/features/auth/ui/NicknameInput.tsx
  src/features/auth/ui/UserInfoRegistrationForm.tsx
  src/features/marking/ui/markingItem.tsx
  src/mocks/handler.ts
  src/pages/my-page/setting/edit-info/page.tsx
  src/shared/lib/format.ts
  src/shared/lib/index.ts
Labels: 👶 기능

#341 [Refactor] useMapStore에서 mapInfo 삭제
  src/features/map/store/map.ts
  src/widgets/map/ui/googleMaps.tsx
  src/widgets/map/ui/mapInitializer.tsx
Labels: ⚒️ 리팩토링

#332 [Feat] 연령대 변경 API 로직 추가
  src/entities/auth/api/getMyInfo.ts
  src/features/auth/constants/form.ts
  src/features/setting/api/index.ts
  src/features/setting/api/putChangeAge.tsx
  src/features/setting/constants/endpoint.ts
  src/features/setting/ui/changeAgeButton.tsx
  src/features/setting/ui/index.ts
  src/mocks/data/myInfo.json
  src/mocks/handler.ts
  src/pages/my-page/setting/edit-info/page.tsx
Labels: 👶 기능

#334 [Feat] 성별 변경 API 로직 추가
  src/entities/auth/api/getMyInfo.ts
  src/features/auth/constants/form.ts
  src/features/setting/api/index.ts
  src/features/setting/api/putChangeGender.ts
  src/features/setting/constants/endpoint.ts
  src/features/setting/ui/genderChangeButton.tsx
  src/features/setting/ui/index.ts
  src/mocks/handler.ts
  src/pages/my-page/setting/edit-info/page.tsx
Labels: 👶 기능

#333 [Feat] 회원 탈퇴 기능 API 로직 추가
  src/features/setting/api/deleteAccount.tsx
  src/features/setting/api/index.ts
  src/features/setting/constants/endpoint.ts
  src/features/setting/hooks/index.ts
  src/features/setting/hooks/usePasswordCheckModal.tsx.tsx
  src/features/setting/store/passwordCheckForm.ts
  src/features/setting/ui/accountCancellationModal.tsx
  src/features/setting/ui/passwordCheckModal.stories.tsx
  src/features/setting/ui/passwordCheckModal.tsx
  src/mocks/handler.ts
Labels: 👶 기능

#344 [Feat] 강아지 정보 수정 API 기능 추가
  src/entities/profile/api/getProfile.ts
  src/entities/profile/ui/dashboard.tsx
  src/features/auth/api/postPetInfo.ts
  src/features/auth/store/petInformationForm.ts
  src/features/auth/ui/dashboard.tsx
  src/features/auth/ui/index.ts
  src/features/auth/ui/petInformationForm.tsx
  src/features/setting/api/index.ts
  src/features/setting/api/putChangePetInformation.ts
  src/features/setting/constants/endpoint.ts
  src/features/setting/hooks/useChangePetInfoModal.tsx
  src/mocks/data/user.json
  src/mocks/handler.ts
  src/pages/sign-up/pet-info/page.tsx
  src/widgets/profile/ui/dashboard.tsx
Labels: 👶 기능, ⚒️ 리팩토링

#340 [Feat] 동네 정보 수정 기능 구현
  src/entities/auth/api/getMyInfo.ts
  src/features/auth/store/region.ts
  src/features/auth/ui/UserInfoRegistrationForm.tsx
  src/features/auth/ui/index.ts
  src/features/auth/ui/regionModal.stories.tsx
  src/features/auth/ui/regionModal.tsx
  src/features/setting/api/index.ts
  src/features/setting/api/postChangeRegion.ts
  src/features/setting/constants/endpoint.ts
  src/features/setting/hooks/index.ts
  src/features/setting/hooks/useChangeRegionModal.tsx
  src/features/setting/ui/index.ts
  src/features/setting/ui/regionChangeButton.tsx
  src/mocks/data/myInfo.json
  src/mocks/data/regionList.json
  src/mocks/handler.ts
  src/pages/my-page/setting/edit-info/page.tsx
Labels: 👶 기능

#347 [Hotfix] GenderChangeButton 잘못 선언된 타입 변경
  src/features/setting/ui/genderChangeButton.tsx
Labels: 🐛 버그

#350 [Feat] 서버에 요청 보내는 apiClient 객체 생성
  src/shared/lib/apiClient.ts
  src/shared/lib/error.ts
  src/shared/lib/index.ts
Labels: 👶 기능, ⚒️ 리팩토링

#351 [Hotfix] 풀페이지 모달 스타일 수정
  src/entities/auth/ui/SignUpLandingModal.tsx
  src/features/setting/hooks/useChangePetInfoModal.tsx
  src/features/setting/ui/accountCancellationModal.tsx
  src/shared/ui/modal/Modal.styles.ts
  src/shared/ui/modal/Modal.tsx
Labels: 🐛 버그

#352 [Hotfix] useMutation 에게 callback 으로 전달 된 onClose 가 현재 열려 있는 모달을 바라보지 못하는 문제 수정
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/features/auth/api/putChangeNickname.ts
  src/features/auth/ui/ChangeNicknameModal.tsx
  src/features/marking/api/postMarkingForm.tsx
  src/features/marking/api/postTempMarkingForm.tsx
  src/features/marking/ui/markingFormModal.tsx
  src/features/setting/api/putChangePassword.tsx
  src/features/setting/api/putChangePetInformation.ts
  src/features/setting/api/putSetPassword.tsx
  src/features/setting/hooks/useChangePetInfoModal.tsx
  src/features/setting/hooks/useChangeRegionModal.tsx
  src/features/setting/ui/passwordChangeModal.tsx
  src/features/setting/ui/passwordSetModal.tsx
  src/shared/lib/overlay.ts
Labels: 🐛 버그

#367 [Hotfix] 센터 모달 스타일 오타로 인해 스타일 깨지는 문제 수정
  src/shared/ui/modal/Modal.styles.ts
Labels: 🐛 버그

#368 [Feat] useSnackbar 커스텀 훅 기능 수정 + 기존 스낵바 사용 하던 컴포넌트들에 적용
  src/app/OverlayPortal.tsx
  src/entities/map/ui/index.ts
  src/entities/map/ui/mapSnackBar.tsx
  src/entities/map/ui/mapSnackbar.tsx
  src/features/auth/ui/ChangeNicknameModal.tsx
  src/features/auth/ui/LoginForm.stories.tsx
  src/features/auth/ui/LoginForm.tsx
  src/features/auth/ui/SignUpByEmailForm.tsx
  src/features/auth/ui/UserInfoRegistrationForm.tsx
  src/features/auth/ui/petInformationForm.tsx
  src/features/map/ui/mapControlButton.tsx
  src/features/marking/api/postAddMarking.tsx
  src/features/marking/api/postAddTempMarking.tsx
  src/features/setting/api/putChangePassword.tsx
  src/features/setting/api/putSetPassword.tsx
  src/features/setting/ui/logoutModal.tsx
  src/features/setting/ui/setting.tsx
  src/shared/constants/index.ts
  src/shared/lib/index.ts
  src/shared/lib/overlay.tsx
  src/shared/lib/snackbar.tsx
  src/shared/store/overlay.ts
  src/shared/ui/snackbar/Snackbar.stories.tsx
  src/shared/ui/snackbar/Snackbar.tsx
Labels: 👶 기능

#364 [Feat] Profile 대시보드 로직 변경 + 404 페이지 생성
  src/app/DevTools.tsx
  src/app/FooterNavigationBar.tsx
  src/app/router.tsx
  src/entities/profile/api/getProfile.ts
  src/features/setting/hooks/useSettingPermission.tsx
  src/mocks/handler.ts
  src/pages/[nickname]/index.ts
  src/pages/[nickname]/notFoundUser.tsx
  src/pages/[nickname]/page.tsx
  src/pages/my-page/myPage.stories.tsx
  src/pages/my-page/page.tsx
  src/pages/my-page/setting/manage-account/index.ts
  src/pages/setting/SettingPage.stories.tsx
  src/pages/setting/edit-info/index.ts
  src/pages/setting/edit-info/page.tsx
  src/pages/setting/index.ts
  src/pages/setting/manage-account/index.ts
  src/pages/setting/manage-account/page.tsx
  src/pages/setting/page.tsx
  src/shared/constants/index.ts
  src/shared/lib/profile.ts
  src/widgets/profile/ui/ProfileOverView.stories.tsx
  src/widgets/profile/ui/dashboard.tsx
Labels: 👶 기능

#371 [Hotfix] 닉네임 변경 모달 버그 수정
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/features/auth/api/putChangeNickname.ts
  src/features/auth/lib/validate.ts
  src/features/auth/ui/ChangeNicknameModal.tsx
  src/features/auth/ui/NicknameInput.tsx
  src/mocks/handler.ts
  src/pages/setting/edit-info/page.tsx
Labels: 🐛 버그

#372 [Feat] GetProfile 서버 변경 사항에 맞춰 수정
  src/entities/marking/ui/dashboard.tsx
  src/entities/profile/api/getProfile.ts
  src/entities/profile/ui/dashboard.tsx
  src/mocks/data/user.json
  src/mocks/handler.ts
  src/pages/[nickname]/page.tsx
  src/widgets/profile/ui/dashboard.tsx
Labels: 👶 기능

#374 [Feat] 동네 모달 에러 스낵바 처리
  src/features/auth/ui/regionModal.tsx
Labels: 👶 기능

#375 [Refactor] 동네마킹 검색 api 수정에 따라 MarkingItem과 useGetMarkingList 수정
  src/app/FooterNavigationBar.tsx
  src/entities/marking/api/getMarkingList.ts
  src/entities/marking/constants/index.ts
  src/features/map/ui/mapMarkers.tsx
  src/mocks/data/markingList.json
  src/mocks/data/markingList.ts
  src/mocks/handler.ts
Labels: ⚒️ 리팩토링

#370 [Feat] AccessToken 만료 시 쿼리 새롭게 요청하는 로직 생성
  src/app/ReactQueryProvider/useCreateQueryClient.ts
Labels: 👶 기능

#376 [Feat] Following , Followers 낙관적 업데이트 포함 퍼블리싱
  src/app/router.tsx
  src/entities/follow/api/getFollowerList.ts
  src/entities/follow/api/getFollowingList.ts
  src/entities/follow/api/index.ts
  src/entities/follow/constants/endpoint.ts
  src/entities/follow/constants/index.ts
  src/entities/profile/api/getProfile.ts
  src/entities/profile/ui/dashboard.tsx
  src/features/follow/ui/FollowingButton.tsx
  src/features/follow/ui/UnFollowingButton.tsx
  src/features/follow/ui/deleteFollowerButton.tsx
  src/features/follow/ui/index.ts
  src/mocks/data/followers.ts
  src/mocks/data/followings.ts
  src/mocks/data/user.json
  src/mocks/data/user.ts
  src/mocks/handler.ts
  src/pages/[nickname]/follower/index.ts
  src/pages/[nickname]/follower/page.tsx
  src/pages/[nickname]/following/index.ts
  src/pages/[nickname]/following/page.tsx
  src/shared/constants/index.ts
  src/widgets/follow/followList.tsx
  src/widgets/follow/followNavigationBar.tsx
  src/widgets/follow/followerUserItem.tsx
  src/widgets/follow/followingUserItem.tsx
  src/widgets/follow/index.ts
Labels: 👶 기능

#381 [Hotfix] 동네 수정 엔드포인트 변경
  src/features/setting/constants/endpoint.ts
Labels: 🐛 버그

#379 [Feat] 무한 스크롤 훅 생성 , 팔로잉 팔로우 리스트 무한 스크롤 이용한 페이지네이션 구현
  src/pages/[nickname]/follower/page.tsx
  src/pages/[nickname]/following/page.tsx
  src/shared/lib/index.ts
  src/shared/lib/scroll.ts
  src/widgets/follow/followList.tsx
Labels: 👶 기능

#383 [Feat] 팔로잉 , 팔로잉 취소 기능 추가
  src/features/follow/api/deleteFollowing.ts
  src/features/follow/api/index.ts
  src/features/follow/api/postFollowing.ts
  src/features/follow/constants/endpoint.ts
  src/features/follow/constants/index.ts
  src/features/follow/ui/FollowingButton.tsx
  src/features/follow/ui/UnFollowingButton.tsx
  src/mocks/data/followers.ts
  src/mocks/data/followings.ts
  src/mocks/data/otherUser.ts
  src/mocks/data/user.ts
  src/mocks/handler.ts
  src/widgets/follow/followerUserItem.tsx
  src/widgets/follow/followingUserItem.tsx
Labels: 👶 기능

#385 [Feat] 팔로워 삭제 기능 구현
  src/features/follow/api/deleteFollower.ts
  src/features/follow/api/index.ts
  src/features/follow/constants/endpoint.ts
  src/features/follow/ui/deleteFollowerButton.tsx
  src/mocks/data/otherUser.ts
  src/mocks/data/user.ts
  src/mocks/handler.ts
  src/widgets/follow/followerUserItem.tsx
Labels: 👶 기능

#395 [Chore] 사용되지 않는 변수에 대한 eslint 정규표현식 옵션 추가
  .eslintrc.json
  eslint.config.js
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/features/setting/api/putChangeAge.tsx
  src/features/setting/api/putChangeGender.ts
Labels: ⚙️ 환경 설정

#396 [Hotfix] Pet 타입 수정에 대한 타입 컴파일 에러 수정
  src/features/auth/api/postAddPetInfo.ts
  src/features/auth/store/petInformationForm.ts
  src/features/auth/ui/petInformationForm.tsx
  src/features/marking/ui/markingItem.tsx
  src/features/setting/api/putChangePetInfo.ts
  src/features/setting/hooks/useChangePetInfoModal.tsx
Labels: 🐛 버그

#389 [Feat] 프로필 대시보드 마킹 썸네일 생성
  src/entities/marking/ui/dashboard.tsx
  src/entities/marking/ui/index.ts
  src/entities/marking/ui/temporaryMarkingBar.tsx
  src/mocks/data/otherUser.ts
  src/mocks/data/profileMarking.ts
  src/mocks/data/user.ts
  src/mocks/handler.ts
  src/pages/[nickname]/page.tsx
  src/widgets/marking/api/getMarkingThumbnail.ts
  src/widgets/marking/api/index.ts
  src/widgets/marking/constants/index.ts
  src/widgets/marking/ui/index.ts
  src/widgets/marking/ui/markingThumbnailGrid.tsx
Labels: 👶 기능

#391 [Feat] 자동 로그인 기능 구현
  src/app/MainLayout.tsx
  src/app/ReactQueryProvider/errorHandlers.ts
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/app/api.ts
  src/mocks/handler.ts
Labels: 👶 기능

#400 [Feat] 남의 프로필 대시보드 페이지 진입 생성
  src/entities/profile/api/getProfile.ts
  src/features/auth/ui/dashboard.tsx
  src/features/follow/ui/FollowingButton.tsx
  src/features/follow/ui/UnFollowingButton.tsx
  src/features/follow/ui/followingToggle.tsx
  src/features/follow/ui/index.ts
  src/features/profile/ui/index.ts
  src/features/profile/ui/profileLink.tsx
  src/mocks/data/otherUser.ts
  src/mocks/data/user.ts
  src/mocks/handler.ts
  src/pages/[nickname]/follower/page.tsx
  src/pages/[nickname]/following/page.tsx
  src/pages/[nickname]/myProfilePage.tsx
  src/pages/[nickname]/otherProfilePage.tsx
  src/pages/[nickname]/page.tsx
  src/widgets/follow/followItemContainer.tsx
  src/widgets/follow/followList.tsx
  src/widgets/follow/followerUserItem.tsx
  src/widgets/follow/followingUserItem.tsx
  src/widgets/follow/index.ts
  src/widgets/marking/api/getDashboardMarkingThumbnail.ts
  src/widgets/marking/api/index.ts
  src/widgets/marking/ui/markingThumbnailGrid.tsx
  src/widgets/profile/ui/index.ts
  src/widgets/profile/ui/myProfileOverview.tsx
  src/widgets/profile/ui/profileOverview.tsx
Labels: 👶 기능

#399 [Feat] 바운더리 마커 리스트 api 요청
  src/entities/marking/api/getBoundaryMarkerList.ts
  src/entities/marking/api/index.ts
  src/entities/marking/constants/index.ts
  src/features/map/ui/mapMarkers.tsx
  src/mocks/data/markingList.ts
  src/mocks/handler.ts
Labels: 👶 기능

#402 [Hotfix] following , unFollowing 후 사용자 프로필 업데이트 로직 추가
  src/features/follow/api/deleteFollowing.ts
  src/features/follow/api/postFollowing.ts
Labels: 🐛 버그

#406 [Feat] 동네 마킹 바텀시트 무한스크롤 구현
  src/entities/marking/api/getBoundaryMarkerList.ts
  src/entities/marking/api/getMarkingList.ts
  src/features/map/hooks/useResearchMarkingList.ts
  src/widgets/map/ui/mapBottomSheet.tsx
Labels: 👶 기능

#415 [Hotfix] getNextPageParams 계산식 변경
  src/entities/follow/api/getFollowerList.ts
  src/entities/follow/api/getFollowingList.ts
  src/entities/marking/api/getMarkingList.ts
  src/widgets/marking/api/getDashboardMarkingThumbnail.ts
Labels: 🐛 버그

#414 [Hotfix] API_BASE_URL 붙어있지 않은 엔드포인트 경로 수정
  src/entities/auth/constants/index.ts
  src/features/marking/constants/endPoint.ts
Labels: 🐛 버그

#413 [Hotfix] 남의 프로필 페이지에서 경로 상 닉네임을 렌더링 하도록 변경
  src/pages/[nickname]/otherProfilePage.tsx
Labels: 🐛 버그

#417 [Feat] 좋아요 , 북마크 토글 생성
  src/features/marking/api/deleteLikeMarking.ts
  src/features/marking/api/deleteSavedMarking.ts
  src/features/marking/api/postLikeMarking.ts
  src/features/marking/api/postSaveMarking.ts
  src/features/marking/constants/endPoint.ts
  src/features/marking/ui/index.ts
  src/features/marking/ui/markingBookmarkToggle.tsx
  src/features/marking/ui/markingItem.stories.tsx
  src/features/marking/ui/markingItem.tsx
  src/features/marking/ui/markingLikeToggle.tsx
  src/mocks/handler.ts
Labels: 👶 기능

#423 [Feat] 이 장소 마킹 바텀 시트 기능 구현 (클러스터링 제외)
  src/app/FooterNavigationBar.tsx
  src/app/router.tsx
  src/entities/map/ui/customMarker.tsx
  src/entities/marking/api/getBoundaryMarkerList.ts
  src/entities/marking/api/getMarkingList.ts
  src/features/map/constants/index.ts
  src/features/map/hooks/useResearchMarkingList.ts
  src/features/map/ui/mapMarkers.tsx
  src/features/marking/ui/markingFilter.tsx
  src/shared/constants/index.ts
  src/widgets/map/constants/index.ts
  src/widgets/map/ui/index.ts
  src/widgets/map/ui/localMarkingList.tsx
  src/widgets/map/ui/mapBottomSheet.tsx
  src/widgets/map/ui/mapInitializer.tsx
  src/widgets/map/ui/markingList.tsx
  src/widgets/map/ui/placeMarkingList.tsx
Labels: 👶 기능

#422 [Feat] 임시 저장 목록 불러오기 , 수정하기 , 삭제하기 기능 추가
  src/app/router.tsx
  src/entities/marking/api/getTemporaryMarkingList.ts
  src/entities/marking/api/index.ts
  src/entities/marking/constants/index.ts
  src/entities/marking/ui/temporaryMarkingBar.tsx
  src/features/marking/api/deleteTemporaryMarking.ts
  src/features/marking/api/index.ts
  src/features/marking/api/postAddTempMarking.tsx
  src/features/marking/api/putModifyTempMarking.ts
  src/features/marking/constants/endPoint.ts
  src/features/marking/store/index.ts
  src/features/marking/store/markingForm.ts
  src/features/marking/store/tempMarkingForm.tsx
  src/features/marking/ui/deleteTemporaryMarkingButton.tsx
  src/features/marking/ui/index.ts
  src/features/marking/ui/markingFormModal.tsx
  src/features/marking/ui/tempMarkingFormModal.tsx
  src/mocks/data/tempMarkingList.ts
  src/mocks/data/user.ts
  src/mocks/handler.ts
  src/pages/temporary-marking/index.ts
  src/pages/temporary-marking/page.tsx
  src/shared/assets/delete.svg
  src/shared/constants/index.ts
  src/shared/ui/icon/index.ts
  src/shared/ui/modal/Modal.tsx
  src/widgets/marking/ui/index.ts
  src/widgets/marking/ui/temporaryMarkingItem.tsx
Labels: 👶 기능, 🐛 버그

#429 [Refactor] 임시 마킹 api url 오타 수정
  src/entities/marking/api/getTemporaryMarkingList.ts
Labels: ⚒️ 리팩토링

#428 [Refactor] 맵의 url를 관리하는 커스텀 훅 리팩토링
  src/entities/marking/api/getBoundaryMarkerList.ts
  src/entities/marking/api/getMarkingList.ts
  src/features/map/hooks/index.ts
  src/features/map/hooks/useGetMapCurrentBounds.ts
  src/features/map/hooks/useMapQueryParams.ts
  src/features/map/hooks/useResearchMarkingList.ts
  src/features/map/ui/mapMarkers.tsx
  src/features/map/ui/markingResearchButton.tsx
  src/features/marking/ui/markingFilter.tsx
  src/widgets/map/ui/localMarkingList.tsx
  src/widgets/map/ui/mapInitializer.tsx
  src/widgets/map/ui/placeMarkingList.tsx
Labels: 👶 기능
