Repository dogandme/frontend, pull requests merged in 2024-08, with the labels that each got.

#9 [Chore] 색상 토큰과 폰트 토큰 설정
  public/fonts/PretendardVariable.woff2
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: ⚙️ 환경 설정

#14 [Feat] design token 설정
  src/global.css
  src/index.css
  tailwind.config.js
Labels: 👶 기능

#16 [Chore] storybook tailwind 환경 설정
  .storybook/preview.ts
  tailwind.config.js
Labels: ⚙️ 환경 설정

#19 [Refactor] font weight 오타 수정
  src/global.css
Labels: ⚒️ 리팩토링

#21 [Feat] 인풋 디자인 시스템 생성
  chromatic.config.json
  src/global.css
  src/shared/assets/calender.svg
  src/shared/ui/input/Input.stories.tsx
  src/shared/ui/input/Input.tsx
  src/shared/ui/input/index.ts
  src/shared/ui/input/input.styles.ts
  src/shared/ui/textarea/TextArea.stories.tsx
  src/shared/ui/textarea/TextArea.styles.tsx
  src/shared/ui/textarea/TextArea.tsx
  src/shared/ui/textarea/index.ts
Labels: 👶 기능

#20 [Feat] Button 컴포넌트 생성
  src/shared/ui/button/Button.stories.tsx
  src/shared/ui/button/Button.tsx
  src/shared/ui/button/button.styles.ts
  src/shared/ui/button/index.ts
  tailwind.config.js
Labels: 👶 기능

#29 [Feat] / 경로 전체 레이아웃 추가
  src/app/router.tsx
  src/pages/index.ts
  src/pages/layout.tsx
  src/pages/page.tsx
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: 👶 기능

#34 [Feat] GNB 공통 컴포넌트 개발
  src/shared/ui/navigationbar/Navigation.style.ts
  src/shared/ui/navigationbar/NavigationBar.stories.tsx
  src/shared/ui/navigationbar/NavigationBar.tsx
  src/shared/ui/navigationbar/index.ts
Labels: 👶 기능

#38 [Feat] Input , TextArea 변경
  src/shared/ui/input/input.styles.ts
  src/shared/ui/textarea/TextArea.tsx
Labels: 👶 기능

#37 [Feat] Icon 컴포넌트
  .storybook/main.ts
  package-lock.json
  package.json
  src/global.css
  src/shared/assets/email.svg
  src/shared/constants/index.ts
  src/shared/ui/button/Button.stories.tsx
  src/shared/ui/button/Button.tsx
  src/shared/ui/icon/Icon.stories.tsx
  src/shared/ui/icon/Icon.tsx
  src/shared/ui/icon/index.ts
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 👶 기능

#40 [Feat] Badge 컴포넌트 생성
  src/shared/ui/badge/Badge.stories.tsx
  src/shared/ui/badge/Badge.tsx
  src/shared/ui/badge/badge.styles.ts
  src/shared/ui/badge/index.ts
Labels: 👶 기능

#44 [Feat] IconButton 컴포넌트 생성
  src/shared/ui/button/IconButton.stories.tsx
  src/shared/ui/button/IconButton.tsx
  src/shared/ui/button/iconButton.style.ts
  src/shared/ui/button/index.ts
Labels: 👶 기능

#46 [Refactor] IconButton에서 SelectedIconButton으로 네이밍 변경
  src/shared/ui/button/IconButton.stories.tsx
  src/shared/ui/button/SelectedIconButton.stories.tsx
  src/shared/ui/button/SelectedIconButton.tsx
  src/shared/ui/button/index.ts
  src/shared/ui/button/selectedIconButton.style.ts
Labels: ⚒️ 리팩토링

#47 [Refactor] Button 컴포넌트 props에 fullWidth 추가
  src/shared/ui/button/Button.stories.tsx
  src/shared/ui/button/Button.tsx
Labels: ⚒️ 리팩토링

#57 [Refactor] router 경로 상수 생성
  src/app/router.tsx
  src/shared/constants/index.ts
Labels: ⚒️ 리팩토링

#58 [Feat] useDebounce 훅 추가
  src/shared/lib/index.ts
  src/shared/ui/input/Input.stories.tsx
Labels: 👶 기능

#59 [Chore] React Query 도입
  src/app/QueryClient.tsx
  src/main.tsx
Labels: ⚙️ 환경 설정

#61 [Feat] /login 경로 페이지 개발
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/preview.tsx
  src/app/router.tsx
  src/entities/auth/assets/google-icon.svg
  src/entities/auth/assets/index.ts
  src/entities/auth/assets/naver-icon.svg
  src/entities/auth/ui/index.ts
  src/features/auth/api/index.ts
  src/features/auth/api/login.ts
  src/features/auth/constants/endpoint.ts
  src/features/auth/constants/index.ts
  src/features/auth/ui/hyperlinks.stories.tsx
  src/features/auth/ui/hyperlinks.tsx
  src/features/auth/ui/index.ts
  src/pages/layout.tsx
  src/pages/login/index.ts
  src/pages/login/layout.tsx
  src/pages/login/login.stories.tsx
  src/pages/login/page.tsx
  src/shared/assets/ward-left.svg
  src/shared/store/auth.ts
  src/shared/store/indxe.ts
  src/shared/ui/icon/index.ts
  src/widgets/navigationbar/ui/BackwardNavigationBar.tsx
  src/widgets/navigationbar/ui/index.ts
  src/widgets/navigationbar/ui/navigationbar.stories.tsx
Labels: 👶 기능, ⚙️ 환경 설정

#64 [Feat] 이메일 회원가입 페이지 생성 및 이메일 검증 로직 구현
  src/app/router.tsx
  src/entities/auth/ui/index.ts
  src/features/auth/model/index.ts
  src/features/auth/model/useSignUpByEmailForm.ts
  src/features/auth/ui/SignUpByEmailForm.stories.tsx
  src/features/auth/ui/SignUpByEmailForm.tsx
  src/features/auth/ui/index.ts
  src/pages/sign-up/index.ts
  src/pages/sign-up/page.tsx
  src/shared/assets/visibility-off.svg
Labels: 👶 기능

#68 [Hotfix] Input,TextArea stausText 높이 수정 ,BackwardNavigationBar props 수정 , storybook addon 수정
  .storybook/main.ts
  src/shared/ui/input/Input.stories.tsx
  src/shared/ui/input/input.styles.ts
  src/shared/ui/textarea/TextArea.styles.tsx
  src/widgets/navigationbar/ui/BackwardNavigationBar.tsx
Labels: ⚙️ 환경 설정, 🐛 버그

#69 [Refactor] 이메일 회원가입 form 검증 로직 구현
  src/features/auth/model/useSignUpByEmailForm.ts
  src/features/auth/ui/SignUpByEmailForm.stories.tsx
  src/features/auth/ui/SignUpByEmailForm.tsx
  src/pages/sign-up/page.tsx
Labels: 👶 기능, ⚒️ 리팩토링

#73 [Feat] Checkbox 컴포넌트 생성
  src/shared/assets/check-box-outline.svg
  src/shared/assets/check-box.svg
  src/shared/assets/indeterminate.svg
  src/shared/ui/checkbox/Checkbox.stories.tsx
  src/shared/ui/checkbox/Checkbox.tsx
  src/shared/ui/checkbox/index.ts
  src/shared/ui/icon/index.ts
Labels: 👶 기능

#74 [Feat] /signup/pet-info 페이지 개발
  public/default-profile.svg
  src/app/router.tsx
  src/features/auth/constants/form.ts
  src/features/auth/store/form.ts
  src/features/auth/store/index.ts
  src/features/auth/ui/PetInfoForm.tsx
  src/features/auth/ui/index.ts
  src/pages/sign-up/pet-info/index.ts
  src/pages/sign-up/pet-info/page.tsx
  src/pages/sign-up/pet-info/pet-info.stories.tsx
  src/shared/assets/close.svg
  src/shared/assets/edit.svg
  src/shared/ui/chip/SelectChip.stories.tsx
  src/shared/ui/chip/SelectChip.tsx
  src/shared/ui/chip/chip.styles.ts
  src/shared/ui/chip/index.ts
  src/shared/ui/icon/index.ts
  src/widgets/navigationbar/ui/CloseNavigationBar.tsx
  src/widgets/navigationbar/ui/index.ts
  src/widgets/navigationbar/ui/navigationbar.stories.tsx
  vite.config.ts
Labels: 👶 기능, ⚙️ 환경 설정

#75 chore[#70] : msw addon 추가
  .storybook/preview.tsx
  package-lock.json
  package.json
  public/mockServiceWorker.js
Labels: ⚙️ 환경 설정

#79 [Feat] 사용자의 라우트 경로를 추적하기 위한 HistoryTracker 컴포넌트 생성
  src/app/HistoryTracker.tsx
  src/pages/layout.tsx
  src/pages/login/layout.tsx
  src/shared/constants/index.ts
  src/shared/store/auth.ts
  src/shared/store/history.ts
Labels: 👶 기능

#81 [Feat] 이메일 회원가입 api 로직 구현
  src/features/auth/api/login.ts
  src/features/auth/constants/endpoint.ts
  src/features/auth/ui/SignUpByEmailForm.tsx
  src/shared/store/auth.ts
Labels: 👶 기능

#82 [Feat] /login 페이지 OAuth API 기능 추가
  src/features/auth/api/login.ts
  src/features/auth/ui/LoginForm.tsx
  src/features/auth/ui/hyperlinks.tsx
  src/shared/store/auth.ts
Labels: 👶 기능

#83 [Feature] 기본 정보 입력 페이지 view 완성
  src/app/router.tsx
  src/entities/auth/ui/Checkbox.stories.tsx
  src/entities/auth/ui/Checkbox.tsx
  src/entities/auth/ui/SelectOpener.tsx
  src/entities/auth/ui/index.ts
  src/features/auth/ui/UserInfoRegistrationForm.stories.tsx
  src/features/auth/ui/UserInfoRegistrationForm.tsx
  src/features/auth/ui/index.ts
  src/pages/sign-up/user-info/index.ts
  src/pages/sign-up/user-info/page.tsx
  src/shared/assets/arrow-drop-down.svg
  src/shared/assets/map-location-searching.svg
  src/shared/ui/checkbox/Checkbox.stories.tsx
  src/shared/ui/checkbox/Checkbox.tsx
  src/shared/ui/checkbox/index.ts
  src/shared/ui/icon/index.ts
Labels: 👶 기능

#87 [Feature] 기본정보 입력 api 로직 구현
  src/features/auth/api/index.ts
  src/features/auth/api/login.ts
  src/features/auth/api/signUp.ts
  src/features/auth/constants/endpoint.ts
  src/features/auth/ui/UserInfoRegistrationForm.tsx
Labels: 👶 기능

#88 [Refactor] LoginForm 컴포넌트 리팩토링
  src/features/auth/store/form.ts
  src/features/auth/ui/LoginForm.stories.tsx
  src/features/auth/ui/LoginForm.tsx
  src/features/auth/ui/index.ts
  src/pages/login/email/page.tsx
Labels: ⚒️ 리팩토링, ✅ 테스트

#90 [Feat] /sign-up/pet-info 페이지 API 기능 추가
  src/features/auth/api/petinfo.ts
  src/features/auth/constants/endpoint.ts
  src/features/auth/store/form.ts
  src/features/auth/ui/PetInfoForm.stories.tsx
  src/features/auth/ui/PetInfoForm.tsx
  src/features/auth/ui/index.ts
  src/pages/sign-up/pet-info/page.tsx
  src/shared/ui/chip/SelectChip.tsx
Labels: 👶 기능, ⚒️ 리팩토링, ✅ 테스트
