Repository dogandme/frontend, pull requests merged in 2025-01, with the labels that each got.

#563 [Hotfix] postLogout 이 정상적으로 동작하지 않아 무한 재요청 가던 버그 수정
  src/features/setting/api/postLogout.ts
  src/features/setting/ui/logoutModal.tsx
Labels: 🐛 버그

#564 [Hotfix] 사용자 정보 등록 랜딩 모달이 뜨지 않는 문제 해결
  src/entities/auth/ui/signUpLandingModal.tsx
  src/features/auth/api/putAddUserInfo.ts
  src/features/auth/ui/userInfoRegistrationForm.stories.tsx
  src/features/auth/ui/userInfoRegistrationForm.tsx
  src/mocks/handlers/auth.ts
Labels: ⚒️ 리팩토링

#566 [Hotfix] 쿠키 cross origin 에서도 전송되도록 credentials 값 수정
  src/app/api.ts
  src/entities/auth/ui/signUpLandingModal.stories.tsx
  src/features/auth/api/postAddPetInfo.ts
  src/features/auth/api/putAddUserInfo.ts
  src/features/setting/api/postLogout.ts
Labels: 🐛 버그

#568 [Docs] 파일 구조 readme 작성
  README.md
  src/assets/react.svg
  src/entities/map/api/index.ts
  src/entities/map/api/useGetRegionByKeyword.ts
  src/entities/map/api/useGetRegionByLatLng.ts
  src/entities/map/ui/customMarker.tsx
  src/entities/marking/lib/index.ts
  src/entities/marking/lib/useGetMyActivityMarkingList.ts
  src/features/auth/ui/dashboard.tsx
  src/features/map/lib/index.ts
  src/features/map/lib/useCurrentLocation.ts
  src/features/map/lib/useGetMapCurrentBounds.ts
  src/features/map/lib/useMapMode.ts
  src/features/map/lib/useMapQueryParams.ts
  src/features/map/lib/usePlaceQueryParams.ts
  src/features/map/ui/mapControlButton.tsx
  src/features/map/ui/markingResearchButton.tsx
  src/features/marking/api/deleteLikeMarking.ts
  src/features/marking/api/deleteSavedMarking.ts
  src/features/marking/ui/markingFilter.tsx
  src/features/setting/lib/index.ts
  src/features/setting/lib/useChangePetInfoModal.tsx
  src/features/setting/lib/useChangeRegionModal.tsx
  src/features/setting/ui/regionChangeButton.tsx
  src/pages/[nickname]/marking/page.tsx
  src/pages/map/page.tsx
  src/pages/map/place/page.tsx
  src/widgets/map/ui/localMarkingListBottomSheet.tsx
  src/widgets/map/ui/mapInitializer.tsx
  src/widgets/map/ui/myActivityList.tsx
  src/widgets/map/ui/myMarkingListBottomSheet.tsx
  src/widgets/map/ui/placeMarkingListBottomSheet.tsx
Labels: 📗 문서

#569 [Docs] 프로젝트 대표 이미지와 기술 스택 이미지 추가
  README.md
Labels: 📗 문서

#572 [Refactor] mock 이미지 데이터 경로 수정
  src/entities/map/ui/customMarker.tsx
  src/entities/marking/api/getDashboardMarkingThumbnail.ts
  src/entities/marking/api/getMarkingDetail.ts
  src/entities/marking/api/getMarkingList.ts
  src/entities/marking/api/getMyLikedMarkingList.ts
  src/entities/marking/api/getMySavedMarkerList.ts
  src/entities/profile/ui/profileImage.tsx
  src/features/auth/ui/petInformationForm.tsx
  src/features/marking/ui/editMarkingFormModal.tsx
  src/mocks/data/getRandomImg.ts
  src/mocks/data/markerList.ts
  src/mocks/data/markingList.ts
  src/mocks/data/myMark.ts
  src/mocks/data/profileMarking.ts
  src/mocks/data/tempMarkingList.ts
  src/mocks/data/userMarkingList.ts
  src/widgets/marking/ui/temporaryMarkingItem.tsx
Labels: ⚒️ 리팩토링

#573 [Feat] 내 활동 msw 생성 및 리팩토링
  src/features/marking/api/deleteLikeMarking.ts
  src/features/marking/api/deleteSavedMarking.ts
  src/features/marking/api/postLikeMarking.ts
  src/features/marking/api/postSaveMarking.ts
  src/mocks/data/getRandomImg.ts
  src/mocks/data/markerList.ts
  src/mocks/data/markingList.ts
  src/mocks/data/myMark.ts
  src/mocks/data/otherUser.ts
  src/mocks/data/profileMarking.ts
  src/mocks/data/randomDogImageList.ts
  src/mocks/data/tempMarkingList.ts
  src/mocks/data/user.ts
  src/mocks/data/userMarkingList.ts
  src/mocks/handlers/follow.ts
  src/mocks/handlers/marking.ts
  src/mocks/handlers/profile.ts
  src/mocks/handlers/setting.ts
  src/mocks/utils/index.ts
  src/widgets/marking/ui/markingItem.tsx
Labels: 👶 기능, ⚒️ 리팩토링, 🐛 버그

#575 [Refactor] Input trailingNode , leadingNode 타입 튜플로 변경
  src/shared/ui/input/input.stories.tsx
  src/shared/ui/input/input.tsx
Labels: ⚒️ 리팩토링

#577 [Hotfix] 바텀 시트 경고 제거하기 위해 padding , paddingBottom 스타일 제거하고 모두 padding direciton 으로 스타일 변경
  src/widgets/map/ui/mapBottomSheet.tsx
Labels: 🐛 버그

#584 [Refactor] 네비게이션 바 컴포넌트 리팩토링
  src/pages/[nickname]/myProfilePage.tsx
  src/shared/ui/navigationBar/backwardNavigationBar.tsx
  src/shared/ui/navigationBar/closeNavigationBar.tsx
  src/shared/ui/navigationBar/navigationBar.tsx
Labels: ⚒️ 리팩토링

#586 [Refacor] RegionChangeButton html 표준에 맞춰 리팩토링
  src/features/setting/ui/regionChangeButton.tsx
  src/pages/setting/edit-info/page.tsx
Labels: ⚒️ 리팩토링

#588 [Hotfix] 탈퇴하기와 로그아웃의 msw handler 수정
  src/features/setting/api/deleteAccount.ts
  src/mocks/handlers/setting.ts
Labels: 🐛 버그

#582 [Docs] 기능 설명 작성
  README.md
Labels: 📗 문서

#592 [Docs] 맵 기능, 프로필, 팔로잉 페이지 readme 작성
  README.md
  src/widgets/marking/ui/markingItem.tsx
Labels: 📗 문서

#593 [Refactor] react-hook-form 도입
  package-lock.json
  package.json
  src/entities/auth/ui/input.tsx
  src/features/auth/@x/setting.ts
  src/features/auth/api/postCheckDuplicateNickname.ts
  src/features/auth/constants/form.ts
  src/features/auth/constants/message.ts
  src/features/auth/lib/index.ts
  src/features/auth/lib/validate.ts
  src/features/auth/store/form.ts
  src/features/auth/store/index.ts
  src/features/auth/store/signUpByEmailForm.ts
  src/features/auth/store/verifyEmail.tsx
  src/features/auth/ui/exitConfirmationModal.tsx
  src/features/auth/ui/index.ts
  src/features/auth/ui/loginForm.stories.tsx
  src/features/auth/ui/loginForm.tsx
  src/features/auth/ui/nicknameInput.tsx
  src/features/auth/ui/signUpByEmailForm.stories.tsx
  src/features/auth/ui/signUpByEmailForm.tsx
  src/features/auth/ui/userInfoRegistrationForm.stories.tsx
  src/features/auth/ui/userInfoRegistrationForm.tsx
  src/features/setting/api/putChangeNickname.ts
  src/features/setting/api/putChangePassword.ts
  src/features/setting/api/putSetPassword.ts
  src/features/setting/constants/index.ts
  src/features/setting/constants/message.ts
  src/features/setting/store/index.ts
  src/features/setting/store/passwordChangeForm.ts
  src/features/setting/store/passwordCheckForm.ts
  src/features/setting/store/passwordSetForm.ts
  src/features/setting/ui/changeNicknameModal.tsx
  src/features/setting/ui/passwordChangeModal.stories.tsx
  src/features/setting/ui/passwordChangeModal.tsx
  src/features/setting/ui/passwordCheckModal.tsx
  src/features/setting/ui/passwordSetModal.tsx
  src/mocks/handlers/auth.ts
  src/pages/login/email/page.tsx
  src/pages/sign-up/page.tsx
  src/shared/ui/modal/modal.tsx
Labels: ⚒️ 리팩토링

#594 [Refactor] Modal 에서 mutation 성공 시 modal 자동으로 닫히던 로직 제거
  src/app/ReactQueryProvider/useCreateQueryClient.ts
  src/features/marking/ui/editMarkingFormModal.tsx
  src/features/marking/ui/markingFormModal.tsx
  src/features/setting/lib/useChangeRegionModal.tsx
  src/features/setting/ui/changeNicknameModal.tsx
  src/features/setting/ui/passwordChangeModal.tsx
  src/features/setting/ui/passwordSetModal.tsx
Labels: ⚒️ 리팩토링

#596 [Docs] readme 에 프로젝트 사용방법 추가
  README.md
Labels: 📗 문서
